# #1. Data Preprocessing 
* 분석에 사용할 데이터를 전처리 하는 과정입니다. 

In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import json
import pathlib
import pickle
import os
current_path = os.getcwd()

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option('float_format', '{:f}'.format)

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl

from datetime import datetime, timedelta
import statistics
import time

import pymysql  
from haversine import haversine
from bisect import bisect_left, bisect_right

from geoband.API import *
import geopandas as gpd
import folium
from folium.plugins import FastMarkerCluster, MarkerCluster
import geoplot as gplt
import geoplot.crs as gcrs
import imageio
import mapclassify as mc

import random
from functools import reduce
from collections import defaultdict

from IPython.display import display
from tqdm.notebook import tqdm
from tqdm import tqdm, tqdm_notebook

import pydeck as pdk
import cufflinks as cf 
cf.go_offline(connected=True)
cf.set_config_file(theme='polar')

import shapely
from shapely import wkt
from shapely.geometry import Polygon, Point, shape

# NLP 
import re
from konlpy.tag import Okt

!pip install glove_python
from glove import Corpus, Glove

# Crawling 
import requests
from bs4 import BeautifulSoup

# Clustering 
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE

from sklearn import metrics
from scipy.spatial.distance import cdist

# 최적화 solver
from mip import Model, xsum, maximize, BINARY  

# font 
import matplotlib.font_manager as font_manager
path = current_path+'/NanumBarunGothic.ttf'
fontprop = font_manager.FontProperties(fname=path)

font_dirs = [current_path, ]
font_files = font_manager.findSystemFonts(fontpaths=font_dirs)
font_list = font_manager.createFontList(font_files)
font_manager.fontManager.ttflist.extend(font_list)
plt.rcParams["font.family"] = 'NanumGothic'
mpl.rcParams['font.family'] = 'NanumBarunGothic'
plt.rc('axes', unicode_minus=False)

Using Python-MIP package version 1.5.3


# 0. Get Compas Data 

In [2]:
start = time.time()

In [3]:
# Data Save 
input_path = pathlib.Path('./input')
if not input_path.is_dir():
    input_path.mkdir()

GetCompasData('SBJ_2102_002', '1', input_path.joinpath('1.수원시_버스정류장.csv'))
GetCompasData('SBJ_2102_002', '2', input_path.joinpath('2.수원시_버스정류장별_승하차이력(1).csv'))
GetCompasData('SBJ_2102_002', '3', input_path.joinpath('3.수원시_버스정류장별_승하차이력(2).csv'))
GetCompasData('SBJ_2102_002', '4', input_path.joinpath('4.수원시_버스정류장별_승하차이력(3).csv'))
GetCompasData('SBJ_2102_002', '5', input_path.joinpath('5.수원시_버스정류장별_승하차이력(4).csv'))
GetCompasData('SBJ_2102_002', '6', input_path.joinpath('6.수원시_버스정류장별_승하차이력(5).csv'))
GetCompasData('SBJ_2102_002', '7', input_path.joinpath('7.수원시_버스정류장별_노선현황.csv'))
GetCompasData('SBJ_2102_002', '8', input_path.joinpath('8.수원시_지하철역_위치정보.csv'))
GetCompasData('SBJ_2102_002', '9', input_path.joinpath('9.수원시_지하철역별_이용현황(2017~2019).csv'))
GetCompasData('SBJ_2102_002', '10', input_path.joinpath('10.수원시_옥외광고물현황.csv'))
GetCompasData('SBJ_2102_002', '11', input_path.joinpath('11.수원시_대기오염도_측정현황.csv'))
GetCompasData('SBJ_2102_002', '12', input_path.joinpath('12.수원시_주차장현황.csv'))
GetCompasData('SBJ_2102_002', '13', input_path.joinpath('13.수원시_기상데이터(2020).csv'))
GetCompasData('SBJ_2102_002', '14', input_path.joinpath('14.수원시_시간대별_유동인구(2020).csv'))
GetCompasData('SBJ_2102_002', '15', input_path.joinpath('15.수원시_성연령별_유동인구(2020).csv'))
GetCompasData('SBJ_2102_002', '16', input_path.joinpath('16.수원시_요일별_유동인구(2020).csv'))
GetCompasData('SBJ_2102_002', '17', input_path.joinpath('17.수원시_인구정보(고령)_격자.geojson'))
GetCompasData('SBJ_2102_002', '18', input_path.joinpath('18.수원시_인구정보(생산가능)_격자.geojson'))
GetCompasData('SBJ_2102_002', '19', input_path.joinpath('19.수원시_인구정보(유소년)_격자.geojson'))
GetCompasData('SBJ_2102_002', '20', input_path.joinpath('20.수원시_교통노드.geojson'))
GetCompasData('SBJ_2102_002', '21', input_path.joinpath('21.수원시_교통링크.geojson'))
GetCompasData('SBJ_2102_002', '22', input_path.joinpath('22.수원시_상세도로망_LV6.geojson'))
GetCompasData('SBJ_2102_002', '23', input_path.joinpath('23.수원시_평일_일별_시간대별_추정교통량_LV6.csv'))
GetCompasData('SBJ_2102_002', '24', input_path.joinpath('24.수원시_평일_일별_혼잡빈도강도_LV6.csv'))
GetCompasData('SBJ_2102_002', '25', input_path.joinpath('25.수원시_평일_일별_혼잡시간강도_LV6.csv'))
GetCompasData('SBJ_2102_002', '26', input_path.joinpath('26.수원시_인도(2017).geojson'))
GetCompasData('SBJ_2102_002', '27', input_path.joinpath('27.수원시_도로명주소(건물).geojson'))
GetCompasData('SBJ_2102_002', '28', input_path.joinpath('28.수원시_건물연면적_격자.geojson'))
GetCompasData('SBJ_2102_002', '29', input_path.joinpath('29.수원시_법정경계(시군구).geojson'))
GetCompasData('SBJ_2102_002', '30', input_path.joinpath('30.수원시_법정경계(읍면동).geojson'))
GetCompasData('SBJ_2102_002', '31', input_path.joinpath('31.수원시_행정경계(읍면동).geojson'))
GetCompasData('SBJ_2102_002', '32', input_path.joinpath('32.수원시_지적도.geojson'))

In [4]:
# Data Load 
df_01 = pd.read_csv(current_path+'/input/1.수원시_버스정류장.csv')
df_02 = pd.read_csv(current_path+'/input/2.수원시_버스정류장별_승하차이력(1).csv')
df_03 = pd.read_csv(current_path+'/input/3.수원시_버스정류장별_승하차이력(2).csv')
df_04 = pd.read_csv(current_path+'/input/4.수원시_버스정류장별_승하차이력(3).csv')
df_05 = pd.read_csv(current_path+'/input/5.수원시_버스정류장별_승하차이력(4).csv')
df_06 = pd.read_csv(current_path+'/input/6.수원시_버스정류장별_승하차이력(5).csv')
df_07 = pd.read_csv(current_path+'/input/7.수원시_버스정류장별_노선현황.csv')
df_08 = pd.read_csv(current_path+'/input/8.수원시_지하철역_위치정보.csv')
df_09 = pd.read_csv(current_path+'/input/9.수원시_지하철역별_이용현황(2017~2019).csv')
df_10 = pd.read_csv(current_path+'/input/10.수원시_옥외광고물현황.csv')
df_11 = pd.read_csv(current_path+'/input/11.수원시_대기오염도_측정현황.csv')
df_12 = pd.read_csv(current_path+'/input/12.수원시_주차장현황.csv')
df_13 = pd.read_csv(current_path+'/input/13.수원시_기상데이터(2020).csv')
df_14 = pd.read_csv(current_path+'/input/14.수원시_시간대별_유동인구(2020).csv')
df_15 = pd.read_csv(current_path+'/input/15.수원시_성연령별_유동인구(2020).csv')
df_16 = pd.read_csv(current_path+'/input/16.수원시_요일별_유동인구(2020).csv')
df_17 = gpd.read_file(current_path+'/input/17.수원시_인구정보(고령)_격자.geojson')
df_18 = gpd.read_file(current_path+'/input/18.수원시_인구정보(생산가능)_격자.geojson')
df_19 = gpd.read_file(current_path+'/input/19.수원시_인구정보(유소년)_격자.geojson')
df_20 = gpd.read_file(current_path+'/input/20.수원시_교통노드.geojson')
df_21 = gpd.read_file(current_path+'/input/21.수원시_교통링크.geojson')
df_22 = gpd.read_file(current_path+'/input/22.수원시_상세도로망_LV6.geojson')
df_23 = pd.read_csv(current_path+'/input/23.수원시_평일_일별_시간대별_추정교통량_LV6.csv')
df_24 = pd.read_csv(current_path+'/input/24.수원시_평일_일별_혼잡빈도강도_LV6.csv')
df_25 = pd.read_csv(current_path+'/input/25.수원시_평일_일별_혼잡시간강도_LV6.csv')
df_26 = gpd.read_file(current_path+'/input/26.수원시_인도(2017).geojson')
df_27 = gpd.read_file(current_path+'/input/27.수원시_도로명주소(건물).geojson')
df_28 = gpd.read_file(current_path+'/input/28.수원시_건물연면적_격자.geojson')
df_29 = gpd.read_file(current_path+'/input/29.수원시_법정경계(시군구).geojson')
df_30 = gpd.read_file(current_path+'/input/30.수원시_법정경계(읍면동).geojson')
df_31 = gpd.read_file(current_path+'/input/31.수원시_행정경계(읍면동).geojson')
df_32 = gpd.read_file(current_path+'/input/32.수원시_지적도.geojson')

In [5]:
token = "pk.eyJ1IjoiZGx3b3FsczQzMjMiLCJhIjoiY2tscnR3bG95MDJwaDJ2bjUzcTBrc3h4cyJ9.WigDFX0Gm612haaz4zQ2hg"
key = '8H1yac%2Bb0yetY2Waad%2BQIRU43O17onRUd7iR0k2p6%2B4i0yNYn3ym0cXgt3ZqWrR9uFw%2BDu%2B5quHbsXxjpsw5ng%3D%3D'

# 1. Bus Data  

## 1-1. BIS & Sidewalk Filtering (QGIS)
* 전기 및 통신공사 완료된 BIS 설치 정류장만 분석에 이용 
* 최소 보행 공간 확보를 위해, 인도 폭 0 or 4 이상인 정류장만 분석에 이용 

In [6]:
# BIS = 1 & 인도 폭 0 or 4 이상인 정류장 
sidewalk = gpd.read_file(current_path+'/busdata/bus_filter_final.geojson')
sidewalk = sidewalk.drop(["layer", "path", "geometry"], axis=1)
sidewalk = sidewalk.drop_duplicates(["정류장ID"])

print(sidewalk.shape)
sidewalk.head()

(519, 14)


정류장ID                정류장명  정류장유형 환승역타입         위치(동)       쉘터  BIS설치여부      LED      LCD  LED+LCD복합형      알뜰형 임대형(음성)        lon       lat
0  201000345             남수원초등학교     시내    일반  경기도 수원시 세류2동      nan        1      nan      nan         nan 1.000000    None 127.016000 37.251091
1  201000268               곡반중학교     시내    일반   경기도 수원시 곡선동 1.000000        1 1.000000      nan         nan      nan    None 127.034254 37.246081
2  201000357  수원은혜교회.한양수자인파크원아파트     시내    일반   경기도 수원시 금곡동 1.000000        1      nan 1.000000         nan      nan    None 126.953978 37.266016
3  202000090                 화서역  시내,마을    일반  경기도 수원시 화서2동 1.000000        1      nan      nan    1.000000      nan    None 126.990107 37.283895
4  202000092              월드메르디앙     시내    일반  경기도 수원시 우만2동      nan        1      nan      nan    1.000000      nan    None 127.037045 37.280164

## 1-2. tmp : df_01 + df_07 

In [7]:
tmp = sidewalk.merge(df_07[['정류소ID', '운행노선', '중앙차로여부']], how = 'left', left_on = '정류장ID', right_on = '정류소ID', copy = False)
del tmp['정류소ID']

In [8]:
# preprocessing
tmp.환승역타입 = '일반'
tmp.쉘터 = tmp.쉘터.fillna(0)

# LED / LCD / LED+LCD 
tmp.LED = tmp.LED.fillna(0)
tmp.LCD = tmp.LCD.fillna(0)
tmp['LED+LCD복합형'] = tmp['LED+LCD복합형'].fillna(0)

# 알뜰형 / 임대형(음성) 
tmp.알뜰형 = tmp.알뜰형.fillna(0)
tmp['임대형(음성)'] = tmp['임대형(음성)'].fillna(0)

# 운행노선 & 중앙차로여부 없는 데이터 2개 drop 
tmp = tmp.dropna(axis=0)

## 1-3. df_02 ~ df_06 

In [9]:
df_02_06 = pd.concat([df_02, df_03, df_04, df_05, df_06], axis=0, ignore_index = True)
df_02_06.shape

(2508607, 12)

In [10]:
# 노선번호 object 형태로 맞춰주기 
tqdm.pandas()
df_02_06["노선번호"] = df_02_06["노선번호"].progress_apply(lambda x : str(x))

# 동시운행 버스 통합 (ex. '92' : 용남고속 & 수원여객 동시 운행)
df_02_06 = df_02_06.groupby(by=['일자', '정류소ID', '노선번호', '노선유형']).sum([['전체승차건수','초승건수','환승건수','전체하차건수','하차건수','미태그건수']]).reset_index()
df_02_06 = df_02_06.drop(['하차 건수','미태그 건수'], axis=1)

100%|██████████| 2508607/2508607 [00:03<00:00, 785500.93it/s]


In [11]:
# 기존 버스 데이터에 합치기 
bus = df_02_06.merge(tmp, how='left', left_on = '정류소ID', right_on = '정류장ID', copy = True).drop(['정류장ID'], axis=1)

# BIS 미설치 정류장 & 인도 폭 기준 미달 정류장 제외 
bus = bus.dropna(axis=0)

In [12]:
print("df_01 unique 정류장 ID 개수 : ", df_01["정류장ID"].nunique())
print("df_02~06 unique 정류장 ID 개수 : ", df_02_06["정류소ID"].nunique())

print("=====" * 20)
print("합치기 전 unique 정류장 ID 개수 : ", tmp["정류장ID"].nunique())
print("합친 후의 unique 정류장 ID 개수 : ", bus["정류소ID"].nunique())

df_01 unique 정류장 ID 개수 :  1179
df_02~06 unique 정류장 ID 개수 :  1114
합치기 전 unique 정류장 ID 개수 :  518
합친 후의 unique 정류장 ID 개수 :  516


## 1-4. 외부데이터 
* **경기 버스 정보** : http://www.gbis.go.kr/
* [route] GGD_RouteInfo_M.xls : 버스 노선 정보 (기점, 종점 / 주중배차간격, 주말배차간격 / 첫차, 막차 시간) 
* [trans] GGD_RouteStationInfo_M.xls : 노선 경유 정보 (버스 노선 순서) 

In [13]:
route = pd.read_excel(current_path+'/data/GGD_RouteInfo_M.xls')
trans = pd.read_excel(current_path+'/data/GGD_RouteStationInfo_M.xls', sheet_name=[0,1,2])

trans = pd.concat([trans[0], trans[1], trans[2]], axis=0, ignore_index = True)

### (1) 버스 노선 순서 데이터 

In [14]:
# 버스 노선 순서 데이터 
trans2 = trans.rename(columns = {"STATION_ID": "정류소ID", "ROUTE_ID": "노선ID", "ROUTE_NM": "노선번호", "STA_ORDER": "노선순서", "STATION_NM": "정류장명"})
trans2 = trans2.drop(["순번", "MOBILE_NO"], axis=1)

# 노선 번호 전처리 
trans2["노선번호"] = trans2["노선번호"].progress_apply(lambda x : str(x))
trans2["노선번호"] = trans2["노선번호"].progress_apply(lambda x : x.replace("-", "_"))

100%|██████████| 192708/192708 [00:00<00:00, 675368.20it/s]


In [15]:
# Data Merge 
tmp2 = bus.merge(trans2.drop(["정류장명"], axis=1), how='left', on=['정류소ID', '노선번호'])
print("bus+trans shape : ", tmp2.shape , '\n') 
print("원래 데이터의 unique bus 개수 : ", bus.정류소ID.nunique())
print("합친 데이터의 unique bus 개수 : ", tmp2.정류소ID.nunique())
print("=====" * 20)
tmp2.head(2)

bus+trans shape :  (1364613, 25) 

원래 데이터의 unique bus 개수 :  516
합친 데이터의 unique bus 개수 :  516


일자      정류소ID 노선번호     노선유형  전체 승차 건수  초승 건수  환승 건수  전체 하차 건수                  정류장명 정류장유형 환승역타입        위치(동)       쉘터  BIS설치여부      LED      LCD  LED+LCD복합형      알뜰형  임대형(음성)        lon       lat                                               운행노선 중앙차로여부             노선ID      노선순서
0  20200101  200000006   13  일반형시내버스       166    160      6        67  광교공원.경기대수원캠퍼스입구.연무시장    시내    일반  경기도 수원시 연무동 0.000000 1.000000 0.000000 0.000000    1.000000 0.000000 0.000000 127.029464 37.300014  13(수원여객),16(수원여객),16-1(수원여객),16-2(수원여객),32-5(수...  노변정류장 200000037.000000 13.000000
1  20200101  200000006   37  일반형시내버스        36     33      3         0  광교공원.경기대수원캠퍼스입구.연무시장    시내    일반  경기도 수원시 연무동 0.000000 1.000000 0.000000 0.000000    1.000000 0.000000 0.000000 127.029464 37.300014  13(수원여객),16(수원여객),16-1(수원여객),16-2(수원여객),32-5(수...  노변정류장 200000099.000000  1.000000

### (2) 버스 노선 정보 데이터 

In [16]:
route["노선번호"] = route["노선번호"].progress_apply(lambda x : str(x))
route["노선번호"] = route["노선번호"].progress_apply(lambda x : x.replace("-", "_"))

# 이상치 처리 
route = route[route["하행첫차"] != '1899/1']
print(route.shape)

100%|██████████| 3480/3480 [00:00<00:00, 112427.91it/s]

(3479, 15)


In [17]:
# 상행첫차, 상행막차, 하행첫차, 하행막차 type 바꿔주기 
route['상행첫차'] = route['상행첫차'].progress_apply(lambda x: pd.to_datetime(str(x), format='%H:%M'))
route['상행막차'] = route['상행막차'].progress_apply(lambda x: pd.to_datetime(str(x), format='%H:%M'))
route['하행첫차'] = route['하행첫차'].progress_apply(lambda x: pd.to_datetime(str(x), format='%H:%M'))
route['하행막차'] = route['하행막차'].progress_apply(lambda x: pd.to_datetime(str(x), format='%H:%M'))

100%|██████████| 3479/3479 [00:00<00:00, 4917.65it/s]


In [18]:
# 운행시간 구하기 : 막차 - 첫차 
def operation_time(first, last) : 
    if last >= first  : 
        return last - first 
    else : 
        last += timedelta(days=1)
        return last - first 

In [19]:
route["상행운행시간"] = route.progress_apply(lambda x : operation_time(x["상행첫차"], x["상행막차"]), axis=1)
route["하행운행시간"] = route.progress_apply(lambda x : operation_time(x["하행첫차"], x["하행막차"]), axis=1)

100%|██████████| 3479/3479 [00:00<00:00, 5840.82it/s]


In [20]:
# Data Merge 
tmp3 = pd.merge(left=tmp2, right=route.drop(["순번"], axis=1).drop_duplicates('노선ID'), how='left', \
                on=['노선ID','노선번호'])

print("bus+trans+route shape : ", tmp3.shape , '\n') 
print("bus 데이터의 unique bus 개수 : ", bus.정류소ID.nunique())
print("tmp2 데이터의 unique bus 개수 : ", tmp2.정류소ID.nunique())
print("합친 데이터의 unique bus 개수 : ", tmp3.정류소ID.nunique())
print("=====" * 20)
tmp3.head(2)

bus+trans+route shape :  (1364613, 39) 

bus 데이터의 unique bus 개수 :  516
tmp2 데이터의 unique bus 개수 :  516
합친 데이터의 unique bus 개수 :  516


일자      정류소ID 노선번호     노선유형  전체 승차 건수  초승 건수  환승 건수  전체 하차 건수                  정류장명 정류장유형 환승역타입        위치(동)       쉘터  BIS설치여부      LED      LCD  LED+LCD복합형      알뜰형  임대형(음성)        lon       lat                                               운행노선 중앙차로여부             노선ID      노선순서  관할관청  운행업체                    기점    기점_STATION_ID                    종점    종점_STATION_ID   주중배차간격   주말배차간격                상행첫차                상행막차                하행첫차                하행막차          상행운행시간          하행운행시간
0  20200101  200000006   13  일반형시내버스       166    160      6        67  광교공원.경기대수원캠퍼스입구.연무시장    시내    일반  경기도 수원시 연무동 0.000000 1.000000 0.000000 0.000000    1.000000 0.000000 0.000000 127.029464 37.300014  13(수원여객),16(수원여객),16-1(수원여객),16-2(수원여객),32-5(수...  노변정류장 200000037.000000 13.000000   수원시  수원여객                상광교동종점 200000275.000000  칠보고등학교.칠보중학교.극동스타클래스 201000099.000000    5분~7분    5분~7분 1900-01-01 06:00:00 1900-01-01 22:00:00 1900-01-01 05:40:00 1900-01-01 23:10:00 0 days 16:00:00 0 days 17:30:00
1  20200101  200000006   37  일반형시내버스        36     33      3         0  광교공원.경기대수원캠퍼스입구.연무시장    시내    일반  경기도 수원시 연무동 0.000000 1.000000 0.000000 0.000000    1.000000 0.000000 0.000000 127.029464 37.300014  13(수원여객),16(수원여객),16-1(수원여객),16-2(수원여객),32-5(수...  노변정류장 200000099.000000  1.000000   수원시  수원여객  광교공원.경기대수원캠퍼스입구.연무시장 200000006.000000           한국민속촌.보라해링턴 228001646.000000  10분~13분  15분~20분 1900-01-01 04:50:00 1900-01-01 21:40:00 1900-01-01 06:00:00 1900-01-01 23:10:00 0 days 16:50:00 0 days 17:10:00

## 1-5. dataframe split  
* 노선 정보가 있는 데이터만 분석에 이용 

In [21]:
# 결측값 없는 dataframe index 
idx = tmp3.dropna(axis=0).index

final = tmp3.loc[idx]
final_na = tmp3[~tmp3.index.isin(idx)]

# check 
print("* 결측값 제외한 dataframe shape : ", final.shape) 
print("* 결측값 제외한 dataframe unique 버스정류장 개수 :", final.정류소ID.nunique())
print("=====" * 20)
print("* 결측값 있는 dataframe shape : ", final_na.shape)  
print("* 결측값 있는 dataframe unique 버스정류장 개수 :", final_na.정류소ID.nunique())

tmp3.shape[0] == (final.shape[0] + final_na.shape[0])

* 결측값 제외한 dataframe shape :  (1326103, 39)
* 결측값 제외한 dataframe unique 버스정류장 개수 : 516
* 결측값 있는 dataframe shape :  (38510, 39)
* 결측값 있는 dataframe unique 버스정류장 개수 : 173


True

## 1-6. 추가 전처리 

In [22]:
# 일자 data type 바꿔주기 (4~5분 소요)
final['일자'] = final['일자'].progress_apply(lambda x: pd.to_datetime(str(x), format='%Y%m%d'))

100%|██████████| 1326103/1326103 [05:10<00:00, 4275.19it/s]


In [23]:
# 중앙차로여부 dummy 변수로 만들기 
final["중앙차로여부"] = final["중앙차로여부"].progress_apply(lambda x : 1 if x == '중앙차로 정류장' else 0)

100%|██████████| 1326103/1326103 [00:01<00:00, 765108.35it/s]


In [24]:
# 운행노선 & 정류장유형 : 개수 구하기 
final["운행노선"] = final["운행노선"].progress_apply(lambda x : x.split(','))
final["운행노선수"] = final["운행노선"].progress_apply(lambda x : len(x))

final["정류장유형"] = final["정류장유형"].progress_apply(lambda x : x.split(','))
final["정류장유형수"] = final["정류장유형"].progress_apply(lambda x : len(x))

100%|██████████| 1326103/1326103 [00:01<00:00, 732793.77it/s]


## 1-7. Bus Stop Data 
* **busstop** : tmp (버스 고유 정보) + route + trans 
* 일별 정보 없는 **버스 정류장** 데이터

In [25]:
busstop = final.drop(['일자', '전체 승차 건수', '초승 건수', '환승 건수', '전체 하차 건수'], axis=1)
busstop = busstop.drop_duplicates(["정류소ID", "노선번호", '노선유형'])

# 해당 노선의 총 승차건수 데이터 평균 
busstop_tmp = final.groupby(by=['정류소ID', '노선번호', '노선유형']).mean([['전체승차건수','초승건수','환승건수','전체하차건수']]).reset_index()

# Data Merge 
busstop = pd.merge(left=busstop, right=busstop_tmp[['정류소ID', '노선번호', '노선유형', '전체 승차 건수', '초승 건수', '환승 건수', '전체 하차 건수']], 
                   how='left', on=['정류소ID', '노선번호', '노선유형'])

print("bus 노선 정보 dataframe shape : ", busstop.shape , '\n') 
print("합친 데이터의 unique bus 개수 : ", busstop.정류소ID.nunique())
print("=====" * 20)
busstop.head(2)

bus 노선 정보 dataframe shape :  (3926, 40) 

합친 데이터의 unique bus 개수 :  516


정류소ID 노선번호     노선유형                  정류장명 정류장유형 환승역타입        위치(동)       쉘터  BIS설치여부      LED      LCD  LED+LCD복합형      알뜰형  임대형(음성)        lon       lat                                               운행노선  중앙차로여부             노선ID      노선순서  관할관청  운행업체                    기점    기점_STATION_ID                    종점    종점_STATION_ID   주중배차간격   주말배차간격                상행첫차                상행막차                하행첫차                하행막차          상행운행시간          하행운행시간  운행노선수  정류장유형수   전체 승차 건수      초승 건수    환승 건수  전체 하차 건수
0  200000006   13  일반형시내버스  광교공원.경기대수원캠퍼스입구.연무시장  [시내]    일반  경기도 수원시 연무동 0.000000 1.000000 0.000000 0.000000    1.000000 0.000000 0.000000 127.029464 37.300014  [13(수원여객), 16(수원여객), 16-1(수원여객), 16-2(수원여객), 3...       0 200000037.000000 13.000000   수원시  수원여객                상광교동종점 200000275.000000  칠보고등학교.칠보중학교.극동스타클래스 201000099.000000    5분~7분    5분~7분 1900-01-01 06:00:00 1900-01-01 22:00:00 1900-01-01 05:40:00 1900-01-01 23:10:00 0 days 16:00:00 0 days 17:30:00      9       1 212.605479 206.279452 6.326027 51.257534
1  200000006   37  일반형시내버스  광교공원.경기대수원캠퍼스입구.연무시장  [시내]    일반  경기도 수원시 연무동 0.000000 1.000000 0.000000 0.000000    1.000000 0.000000 0.000000 127.029464 37.300014  [13(수원여객), 16(수원여객), 16-1(수원여객), 16-2(수원여객), 3...       0 200000099.000000  1.000000   수원시  수원여객  광교공원.경기대수원캠퍼스입구.연무시장 200000006.000000           한국민속촌.보라해링턴 228001646.000000  10분~13분  15분~20분 1900-01-01 04:50:00 1900-01-01 21:40:00 1900-01-01 06:00:00 1900-01-01 23:10:00 0 days 16:50:00 0 days 17:10:00      9       1  48.726027  43.556164 5.169863  4.813699

# 2. Bus Data Feature Engineering 
1. **tmp** (518, 16) : 버스 정류장 고유 정보 데이터, df_01 + df_07 
2. **busstop** (3921, 36) : tmp (버스 고유 정보) + route + trans
3. **final** (1326103, 43) : 일별 노선 승하차 정보 포함 데이터 

## 2-1. busstop data Feature Engineering 
* 버스 노선 고유 정보 feature engineering 

### (1) 버스 유형 

In [26]:
busstop = pd.get_dummies(busstop, columns=["노선유형"])

### (2) 노선 별 승차 건수 비율 

In [27]:
def div(col1, col2) : 
    try : 
        return col1 / col2 
    except : 
        return 0 

In [28]:
# 초승 환승 전체승차 하차 비율 (a_b비율 = a/b)
busstop["초승_환승비율"] = busstop.progress_apply(lambda x : div(x['초승 건수'], x['환승 건수']), axis=1)
busstop["초승_승차비율"] = busstop.progress_apply(lambda x : div(x['초승 건수'], x['전체 승차 건수']), axis=1)
busstop["초승_하차비율"] = busstop.progress_apply(lambda x : div(x['초승 건수'], x['전체 하차 건수']), axis=1)

busstop["환승_승차비율"] = busstop.progress_apply(lambda x : div(x['환승 건수'], x['전체 승차 건수']), axis=1)
busstop["환승_하차비율"] = busstop.progress_apply(lambda x : div(x['환승 건수'], x['전체 하차 건수']), axis=1)

busstop["승차_하차비율"] = busstop.progress_apply(lambda x : div(x['전체 승차 건수'], x['전체 하차 건수']), axis=1)

100%|██████████| 3926/3926 [00:00<00:00, 17003.19it/s]


### (3) 승차 많은 / 환승 많은 / 하차 많은 버스 노선 
* 분모 : 전체 승차 건수 + 전체 하차 건수 
* 분자 : 승차 건수 / 환승 건수 / 하차 건수 

In [29]:
busstop["전체승하차건수"] = busstop.progress_apply(lambda x : x['전체 승차 건수'] + x['전체 하차 건수'], axis=1)

busstop["승차비율"] = busstop.progress_apply(lambda x : div(x['초승 건수'], x['전체승하차건수']), axis=1)
busstop["환승비율"] = busstop.progress_apply(lambda x : div(x['환승 건수'], x['전체승하차건수']), axis=1)
busstop["하차비율"] = busstop.progress_apply(lambda x : div(x['전체 하차 건수'], x['전체승하차건수']), axis=1)

100%|██████████| 3926/3926 [00:00<00:00, 16277.84it/s]


In [30]:
busstop["승차많은버스"] = busstop["승차비율"].progress_apply(lambda x : 1 if x > 0.65 else 0)
busstop["환승많은버스"] = busstop["환승비율"].progress_apply(lambda x : 1 if x > 0.2 else 0)
busstop["하차많은버스"] = busstop["하차비율"].progress_apply(lambda x : 1 if x > 0.8 else 0)

100%|██████████| 3926/3926 [00:00<00:00, 550288.65it/s]


In [31]:
'''
<mean>
승하차 비율  

<sum>
승하차 건수
노선 유형
승하차 많은 버스 
'''

temp_mean = busstop[['정류소ID'] + list(busstop.columns[busstop.columns.str.contains("비율")])].groupby('정류소ID').mean().reset_index()
temp_sum  = busstop[['정류소ID'] + list(busstop.columns[busstop.columns.str.contains("건수|노선유형|많은")])].groupby('정류소ID').sum().reset_index()

temp_mean.shape, temp_sum.shape

((516, 10), (516, 15))

### (4) 첫차 / 막차 시간 

In [32]:
# 첫차 : 가장 빠른 시간 , 막차 : 가장 늦은 시간 
time1 = busstop.sort_values('상행첫차').groupby('정류소ID').first().reset_index()
time2 = busstop.sort_values('상행막차').groupby('정류소ID').last().reset_index()
time3 = busstop.sort_values('하행첫차').groupby('정류소ID').first().reset_index()
time4 = busstop.sort_values('하행막차').groupby('정류소ID').last().reset_index()

time1.shape, time2.shape, time3.shape, time4.shape

((516, 58), (516, 58), (516, 58), (516, 58))

### (5) Data Merge 
* **busstop** : 버스 정류장 정보, 분석에 필요한 column 만 keep 
* **temp_mean / temp_sum** : 버스 노선 정보 통계량 
* **time** : 첫차 / 막차 시간 

In [33]:
# busstop 
busdf = busstop[['정류소ID', '정류장명', '쉘터', 'LED', 'LCD', 'LED+LCD복합형', '알뜰형', 'lon', 'lat', 
                 '중앙차로여부', '운행노선수', '정류장유형수']].drop_duplicates(['정류소ID']).reset_index(drop=True)  

# temp_mean / temp_sum 
busdf = busdf.merge(temp_mean, how='left', on='정류소ID')
busdf = busdf.merge(temp_sum, how='left', on='정류소ID')

# time 
busdf = busdf.merge(time1[["정류소ID", '상행첫차']], on = '정류소ID', how='left')
busdf = busdf.merge(time2[["정류소ID", '상행막차']], on = '정류소ID', how='left')
busdf = busdf.merge(time3[["정류소ID", '하행첫차']], on = '정류소ID', how='left')
busdf = busdf.merge(time4[["정류소ID", '하행막차']], on = '정류소ID', how='left')

In [34]:
# 버스 정류장 운행 시간 
busdf["상행버스정류장운행시간"] = busdf.progress_apply(lambda x : operation_time(x["상행첫차"], x["상행막차"]), axis=1)
busdf["하행버스정류장운행시간"] = busdf.progress_apply(lambda x : operation_time(x["하행첫차"], x["하행막차"]), axis=1)

# 운행 시간 (hr 기준)
busdf["상행버스정류장운행시간"] = busdf["상행버스정류장운행시간"].progress_apply(lambda x : x.seconds / 3600)
busdf["하행버스정류장운행시간"] = busdf["하행버스정류장운행시간"].progress_apply(lambda x : x.seconds / 3600)

busdf = busdf.drop(['상행첫차', '상행막차', '하행첫차', '하행막차'], axis=1)

100%|██████████| 516/516 [00:00<00:00, 97629.96it/s]


In [35]:
print(busdf.shape)
print("버스 정류장 unique 개수 : ", busdf.정류소ID.nunique())
print("=====" * 20)
busdf.head(3)

(516, 37)
버스 정류장 unique 개수 :  516


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000
2  200000036               풍림아파트입구 1.000000 0.000000 0.000000    1.000000 0.000000 126.995257 37.297929       0      1       2  10.415812 0.912402  0.673753 0.087598 0.064686  0.738438 0.387562 0.037209 0.575229  73.186301  66.775342  6.410959  99.109589                   0               0             0             1             0               0 172.295890       0       0       0    17.833333    17.833333

## 2-2. final Data Feature Engineering 
* 일별 정보 반영 feature engineering 

### (1) 공통 전처리 

In [36]:
final2 = final.copy()
final2 = final2.drop(["정류장유형", "환승역타입", "위치(동)", "쉘터", "BIS설치여부", 'LED', 'LCD', 'LED+LCD복합형', 
                      '알뜰형', '임대형(음성)', 'lon', 'lat', '운행노선', '중앙차로여부', 
                      '정류장명', '노선ID', '노선순서', '관할관청', '운행업체', '기점', '기점_STATION_ID', '종점', '종점_STATION_ID', 
                      '상행첫차', '상행막차', '하행첫차', '하행막차'], axis=1)

In [37]:
print(final2.shape)
final2.head(2)

(1326103, 14)


일자      정류소ID 노선번호     노선유형  전체 승차 건수  초승 건수  환승 건수  전체 하차 건수   주중배차간격   주말배차간격          상행운행시간          하행운행시간  운행노선수  정류장유형수
0 2020-01-01  200000006   13  일반형시내버스       166    160      6        67    5분~7분    5분~7분 0 days 16:00:00 0 days 17:30:00      9       1
1 2020-01-01  200000006   37  일반형시내버스        36     33      3         0  10분~13분  15분~20분 0 days 16:50:00 0 days 17:10:00      9       1

In [38]:
# 배차간격 
def interval(x) : 
    try : 
        itv = x.split("~")
        a, b = int(itv[0][:-1]), int(itv[1][:-1])
        return (a+b)/2
    except :
        return int(x[:-1])

In [39]:
# 분 단위 배차간격 
final2["주중배차간격(분)"] = final2["주중배차간격"].progress_apply(lambda x : interval(x))
final2["주말배차간격(분)"] = final2["주말배차간격"].progress_apply(lambda x : interval(x))

final2 = final2.drop(["주중배차간격", "주말배차간격"], axis=1)

100%|██████████| 1326103/1326103 [00:03<00:00, 365419.86it/s]


In [40]:
final2["주중배차간격_15분"] = final2["주중배차간격(분)"].progress_apply(lambda x : 1 if x < 15 else 0)
final2["주중배차간격_60분"] = final2["주중배차간격(분)"].progress_apply(lambda x : 1 if x > 60 else 0)

final2["주말배차간격_15분"] = final2["주말배차간격(분)"].progress_apply(lambda x : 1 if x < 15 else 0)
final2["주말배차간격_60분"] = final2["주말배차간격(분)"].progress_apply(lambda x : 1 if x > 60 else 0)

100%|██████████| 1326103/1326103 [00:01<00:00, 714438.00it/s]


In [41]:
final2["전체승하차건수"] = final2.progress_apply(lambda x : x['전체 승차 건수'] + x['전체 하차 건수'], axis=1)

final2["상행운행시간"] = final2["상행운행시간"].progress_apply(lambda x : x.total_seconds())
final2["하행운행시간"] = final2["하행운행시간"].progress_apply(lambda x : x.total_seconds())

100%|██████████| 1326103/1326103 [00:14<00:00, 92633.77it/s] 


In [42]:
def getHoliday(year):
    
    '''
    공공데이터포털 공휴일 정보 OPEN API  
    '''
    
    url = f'http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo?solYear={year}&ServiceKey={key}&_type=json&numOfRows=20'
    response = requests.get(url)
    holidays = response.json()['response']['body']['items']['item']
    holidays = pd.DataFrame(holidays)
    holidays['locdate'] = holidays['locdate'].astype(str).apply(lambda x : '-'.join([x[:4], x[4:6], x[6:]]))
    
    return holidays

In [43]:
# 공휴일 
holidays = getHoliday(2020)

final2 = final2.merge(holidays[['locdate', 'isHoliday']], left_on = final2['일자'].dt.date.astype(str), right_on = 'locdate', how = 'left').drop('locdate', axis = 1)
final2['공휴일'] = final2['isHoliday'].progress_apply(lambda x : 1 if x == 'Y' else 0)
final2 = final2.drop(["isHoliday"], axis=1)

# 주말 : 월 0 화 1 수 2 목 3 금 4 토 5 일 6 
final2["주말"] = final2["일자"].progress_apply(lambda x : 1 if x.weekday() in [5,6] else 0)

100%|██████████| 1326103/1326103 [00:10<00:00, 128843.99it/s]


In [44]:
# 주중, 주말, 공휴일 dataframe 
weekday = final2[(final2["주말"] == 0) & (final2["공휴일"] == 0)]  
weekend = final2[final2["주말"] == 1] 
holiday = final2[final2["공휴일"] == 1]  

weekday.shape, weekend.shape, holiday.shape

((914549, 21), (369827, 21), (62158, 21))

In [45]:
# 해당 노선의 총 승차건수 데이터 평균 
weekday = weekday.groupby(by=['정류소ID', '노선번호', '노선유형']).mean([['전체승차건수','초승건수','환승건수','전체하차건수']]).reset_index()
weekend = weekend.groupby(by=['정류소ID', '노선번호', '노선유형']).mean([['전체승차건수','초승건수','환승건수','전체하차건수']]).reset_index()
holiday = holiday.groupby(by=['정류소ID', '노선번호', '노선유형']).mean([['전체승차건수','초승건수','환승건수','전체하차건수']]).reset_index()

print("주중 데이터 shape : {} / 버스 정류장 unique 개수 : {}".format(weekday.shape, weekday.정류소ID.nunique()))
print("주말 데이터 shape : {} / 버스 정류장 unique 개수 : {}".format(weekend.shape, weekend.정류소ID.nunique()))
print("공휴일 데이터 shape : {} / 버스 정류장 unique 개수 : {}".format(holiday.shape, holiday.정류소ID.nunique()))

주중 데이터 shape : (3926, 20) / 버스 정류장 unique 개수 : 516
주말 데이터 shape : (3924, 20) / 버스 정류장 unique 개수 : 516
공휴일 데이터 shape : (3903, 20) / 버스 정류장 unique 개수 : 515


### (2) 대기시간노출도, 배차 횟수, 승차/환승/하차 비율 

#### 주중 

In [46]:
# 대기시간 노출도 = 배차간격 * 승차건수 
def waiting(data, column) : 
    tmp = data[data["주중배차간격_60분"] == 0].groupby(['정류소ID']).max(f'{column}배차간격(분)')[f"{column}배차간격(분)"].reset_index().rename(columns = {f'{column}배차간격(분)': f"평균{column}배차간격"})
    data = data.merge(tmp, on="정류소ID", how="left")
    
    data[f"평균{column}배차간격"] = np.where(pd.notnull(data[f'평균{column}배차간격']) == True, data[f'평균{column}배차간격'], data[f'{column}배차간격(분)'])   
    data[f"{column}대기시간노출도"] = data.apply(lambda x : (x["전체 승차 건수"] * x[f"{column}배차간격(분)"]) if x[f"{column}배차간격_60분"] == 0 else (x["전체 승차 건수"] * x[f"평균{column}배차간격"]), axis=1)
    
    return data 

In [47]:
weekday = waiting(weekday, "주중")

In [48]:
# 주중 
weekday["주중상행배차횟수"] = weekday.progress_apply(lambda x : div(x['상행운행시간'], (x['주중배차간격(분)'] * 60)), axis=1)
weekday["주중하행배차횟수"] = weekday.progress_apply(lambda x : div(x['하행운행시간'], (x['주중배차간격(분)'] * 60)), axis=1)

weekday["주중배차횟수"] = weekday.progress_apply(lambda x : (x["주중상행배차횟수"] + x["주중하행배차횟수"]) / 2, axis=1)
weekday = weekday.drop(["주중상행배차횟수", "주중하행배차횟수"], axis=1)

100%|██████████| 3926/3926 [00:00<00:00, 48560.70it/s]


In [49]:
weekday["주중승차비율"] = weekday.progress_apply(lambda x : div(x['초승 건수'], x['전체승하차건수']), axis=1)
weekday["주중환승비율"] = weekday.progress_apply(lambda x : div(x['환승 건수'], x['전체승하차건수']), axis=1)
weekday["주중하차비율"] = weekday.progress_apply(lambda x : div(x['전체 하차 건수'], x['전체승하차건수']), axis=1)

100%|██████████| 3926/3926 [00:00<00:00, 56119.60it/s]


In [50]:
weekday["주중승차많은버스"] = weekday["주중승차비율"].progress_apply(lambda x : 1 if x > 0.65 else 0)
weekday["주중환승많은버스"] = weekday["주중환승비율"].progress_apply(lambda x : 1 if x > 0.25 else 0)
weekday["주중하차많은버스"] = weekday["주중하차비율"].progress_apply(lambda x : 1 if x > 0.8 else 0)

100%|██████████| 3926/3926 [00:00<00:00, 648913.84it/s]


In [51]:
weekday.head(2)

정류소ID 노선번호     노선유형   전체 승차 건수      초승 건수    환승 건수  전체 하차 건수       상행운행시간       하행운행시간    운행노선수   정류장유형수  주중배차간격(분)  주말배차간격(분)  주중배차간격_15분  주중배차간격_60분  주말배차간격_15분  주말배차간격_60분    전체승하차건수      공휴일       주말  평균주중배차간격   주중대기시간노출도     주중배차횟수   주중승차비율   주중환승비율   주중하차비율  주중승차많은버스  주중환승많은버스  주중하차많은버스
0  200000006   13  일반형시내버스 205.236948 198.522088 6.714859 37.244980 57600.000000 63000.000000 9.000000 1.000000   6.000000   6.000000    1.000000    0.000000    1.000000    0.000000 242.481928 0.000000 0.000000 11.500000 1231.421687 167.500000 0.818709 0.027692 0.153599         1         0         0
1  200000006   16  일반형시내버스   2.210191   1.923567 0.286624  0.726115 48300.000000 48300.000000 9.000000 1.000000 210.000000 210.000000    0.000000    1.000000    0.000000    1.000000   2.936306 0.000000 0.000000 11.500000   25.417197   3.833333 0.655098 0.097614 0.247289         1         0         0

#### 주말 

In [52]:
weekend = waiting(weekend, "주말")

In [53]:
# 주말 
weekend["주말상행배차횟수"] = weekend.progress_apply(lambda x : div(x['상행운행시간'], (x['주말배차간격(분)'] * 60)), axis=1)
weekend["주말하행배차횟수"] = weekend.progress_apply(lambda x : div(x['하행운행시간'], (x['주말배차간격(분)'] * 60)), axis=1)

weekend["주말배차횟수"] = weekend.progress_apply(lambda x : (x["주말상행배차횟수"] + x["주말하행배차횟수"]) / 2, axis=1)
weekend = weekend.drop(["주말상행배차횟수", "주말하행배차횟수"], axis=1)

100%|██████████| 3924/3924 [00:00<00:00, 50337.04it/s]


In [54]:
weekend["주말승차비율"] = weekend.progress_apply(lambda x : div(x['초승 건수'], x['전체승하차건수']), axis=1)
weekend["주말환승비율"] = weekend.progress_apply(lambda x : div(x['환승 건수'], x['전체승하차건수']), axis=1)
weekend["주말하차비율"] = weekend.progress_apply(lambda x : div(x['전체 하차 건수'], x['전체승하차건수']), axis=1)

100%|██████████| 3924/3924 [00:00<00:00, 60596.78it/s]


In [55]:
weekend["주말승차많은버스"] = weekend["주말승차비율"].progress_apply(lambda x : 1 if x > 0.65 else 0)
weekend["주말환승많은버스"] = weekend["주말환승비율"].progress_apply(lambda x : 1 if x > 0.25 else 0)
weekend["주말하차많은버스"] = weekend["주말하차비율"].progress_apply(lambda x : 1 if x > 0.8 else 0)

100%|██████████| 3924/3924 [00:00<00:00, 619413.98it/s]


In [56]:
weekend.head(2)

정류소ID 노선번호     노선유형   전체 승차 건수      초승 건수    환승 건수  전체 하차 건수       상행운행시간       하행운행시간    운행노선수   정류장유형수  주중배차간격(분)  주말배차간격(분)  주중배차간격_15분  주중배차간격_60분  주말배차간격_15분  주말배차간격_60분    전체승하차건수      공휴일       주말  평균주말배차간격   주말대기시간노출도     주말배차횟수   주말승차비율   주말환승비율   주말하차비율  주말승차많은버스  주말환승많은버스  주말하차많은버스
0  200000006   13  일반형시내버스 233.365385 227.769231 5.596154 82.500000 57600.000000 63000.000000 9.000000 1.000000   6.000000   6.000000    1.000000    0.000000    1.000000    0.000000 315.865385 0.057692 1.000000 17.500000 1400.192308 167.500000 0.721096 0.017717 0.261187         1         0         0
1  200000006   16  일반형시내버스   3.952381   3.317460 0.634921  0.238095 48300.000000 48300.000000 9.000000 1.000000 210.000000 210.000000    0.000000    1.000000    0.000000    1.000000   4.190476 0.047619 1.000000 17.500000   69.166667   3.833333 0.791667 0.151515 0.056818         1         0         0

#### 공휴일 

In [57]:
holiday = waiting(holiday, "주말").rename(columns = {"주말대기시간노출도" : "공휴일대기시간노출도"})

In [58]:
# 공휴일 
holiday["공휴일상행배차횟수"] = holiday.progress_apply(lambda x : div(x['상행운행시간'], (x['주말배차간격(분)'] * 60)), axis=1)
holiday["공휴일하행배차횟수"] = holiday.progress_apply(lambda x : div(x['하행운행시간'], (x['주말배차간격(분)'] * 60)), axis=1)

holiday["공휴일배차횟수"] = holiday.progress_apply(lambda x : (x["공휴일상행배차횟수"] + x["공휴일하행배차횟수"]) / 2, axis=1)
holiday = holiday.drop(["공휴일상행배차횟수", "공휴일하행배차횟수"], axis=1)

100%|██████████| 3903/3903 [00:00<00:00, 50017.17it/s]


In [59]:
holiday["공휴일승차비율"] = holiday.progress_apply(lambda x : div(x['초승 건수'], x['전체승하차건수']), axis=1)
holiday["공휴일환승비율"] = holiday.progress_apply(lambda x : div(x['환승 건수'], x['전체승하차건수']), axis=1)
holiday["공휴일하차비율"] = holiday.progress_apply(lambda x : div(x['전체 하차 건수'], x['전체승하차건수']), axis=1)

100%|██████████| 3903/3903 [00:00<00:00, 52119.66it/s]


In [60]:
holiday["공휴일승차많은버스"] = holiday["공휴일승차비율"].progress_apply(lambda x : 1 if x > 0.65 else 0)
holiday["공휴일환승많은버스"] = holiday["공휴일환승비율"].progress_apply(lambda x : 1 if x > 0.25 else 0)
holiday["공휴일하차많은버스"] = holiday["공휴일하차비율"].progress_apply(lambda x : 1 if x > 0.8 else 0)

100%|██████████| 3903/3903 [00:00<00:00, 616748.99it/s]


In [61]:
holiday.head(2)

정류소ID 노선번호     노선유형   전체 승차 건수      초승 건수    환승 건수  전체 하차 건수       상행운행시간       하행운행시간    운행노선수   정류장유형수  주중배차간격(분)  주말배차간격(분)  주중배차간격_15분  주중배차간격_60분  주말배차간격_15분  주말배차간격_60분    전체승하차건수      공휴일       주말  평균주말배차간격  공휴일대기시간노출도    공휴일배차횟수  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스
0  200000006   13  일반형시내버스 185.055556 180.444444 4.611111 70.500000 57600.000000 63000.000000 9.000000 1.000000   6.000000   6.000000    1.000000    0.000000    1.000000    0.000000 255.555556 1.000000 0.333333 17.500000 1110.333333 167.500000 0.706087 0.018043 0.275870          1          0          0
1  200000006   16  일반형시내버스   4.000000   3.555556 0.444444  0.111111 48300.000000 48300.000000 9.000000 1.000000 210.000000 210.000000    0.000000    1.000000    0.000000    1.000000   4.111111 1.000000 0.333333 17.500000   70.000000   3.833333 0.864865 0.108108 0.027027          1          0          0

### (3) Data Merge 

#### 주중 

In [62]:
'''
<mean> 
비율 
배차간격 

<sum> 
승하차 건수 
배차 간격에 대한 버스 개수 
승차/환승/하차 많은 버스 개수 
대기시간노출도 

<min>
평균배차간격 
'''


weekday = weekday.drop(["주말배차간격(분)", "노선번호", "노선유형", "상행운행시간", "하행운행시간", "공휴일", "주말", '운행노선수', '정류장유형수', 
                        '전체 승차 건수', '초승 건수', '환승 건수', '전체 하차 건수'], axis=1)

weekday_tmp1 = weekday[['정류소ID', "주중배차간격(분)", '주중승차비율', '주중환승비율', '주중하차비율']].groupby('정류소ID').mean().reset_index()
weekday_tmp2 = weekday[['정류소ID', "전체승하차건수", '주중배차간격_15분', '주중배차간격_60분', '주중배차횟수', "주중승차많은버스", "주중환승많은버스", "주중하차많은버스", "주중대기시간노출도"]].groupby('정류소ID').sum().reset_index()
weekday_tmp3 = weekday[['정류소ID', "평균주중배차간격"]].groupby('정류소ID').min().reset_index()

weekday_final = weekday_tmp1.merge(weekday_tmp2, on="정류소ID", how="left", copy=False).rename(columns = {"전체승하차건수" : "주중전체승하차건수"})
weekday_final = weekday_final.merge(weekday_tmp3, on="정류소ID", how="left", copy=False)

print(weekday_final.shape)
weekday_final.head()

(516, 14)


정류소ID  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격
0  200000006  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000
1  200000008   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000
2  200000021   8.000000 0.504644 0.036681 0.458675 163.241935    1.000000    0.000000 133.750000         0         0         0  706.935484  8.000000
3  200000036   8.000000 0.390197 0.039952 0.569850 195.915663    1.000000    0.000000 133.750000         0         0         0  674.184739  8.000000
4  200000047 132.583333 0.246525 0.008104 0.745371 268.569520    1.000000    4.000000 135.626170         0         0         4 2365.434593 32.500000

#### 주말

In [63]:
weekend = weekend.drop(["주중배차간격(분)", "노선번호", "노선유형", "상행운행시간", "하행운행시간", "공휴일", "주말", '운행노선수', '정류장유형수', 
                        '전체 승차 건수', '초승 건수', '환승 건수', '전체 하차 건수'], axis=1)

weekend_tmp1 = weekend[['정류소ID', "주말배차간격(분)", '주말승차비율', '주말환승비율', '주말하차비율']].groupby('정류소ID').mean().reset_index()
weekend_tmp2 = weekend[['정류소ID', "전체승하차건수", '주말배차간격_15분', '주말배차간격_60분', '주말배차횟수', "주말승차많은버스", "주말환승많은버스", "주말하차많은버스", "주말대기시간노출도"]].groupby('정류소ID').sum().reset_index()
weekend_tmp3 = weekend[['정류소ID', "평균주말배차간격"]].groupby('정류소ID').min().reset_index()

weekend_final = weekend_tmp1.merge(weekend_tmp2, on="정류소ID", how="left", copy=False).rename(columns = {"전체승하차건수" : "주말전체승하차건수"})
weekend_final = weekend_final.merge(weekend_tmp3, on="정류소ID", how="left", copy=False)

print(weekend_final.shape)
weekend_final.head()

(516, 14)


정류소ID  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격
0  200000006  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000
1  200000008   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000
2  200000021  10.500000 0.516883 0.023945 0.459171  102.798077    1.000000    0.000000 101.904762         0         0         0  583.759615 10.500000
3  200000036  10.500000 0.381641 0.028005 0.590354  123.605769    1.000000    0.000000 101.904762         0         0         0  531.663462 10.500000
4  200000047 134.833333 0.245762 0.010511 0.743727  161.905421    0.000000    4.000000  95.186610         0         0         4 2042.795010 35.000000

#### 공휴일 

In [64]:
holiday = holiday.drop(["주중배차간격(분)", "주말배차간격(분)", "노선번호", "노선유형", "상행운행시간", "하행운행시간", "공휴일", "주말", '운행노선수', '정류장유형수', 
                        '전체 승차 건수', '공휴일배차횟수', '주말배차간격_15분', '주말배차간격_60분', '초승 건수', '환승 건수', '전체 하차 건수'], axis=1)

holiday_tmp1 = holiday[['정류소ID', '공휴일승차비율', '공휴일환승비율', '공휴일하차비율']].groupby('정류소ID').mean().reset_index()
holiday_tmp2 = holiday[['정류소ID', "전체승하차건수", "공휴일승차많은버스", "공휴일환승많은버스", "공휴일하차많은버스", "공휴일대기시간노출도"]].groupby('정류소ID').sum().reset_index()

holiday_final = holiday_tmp1.merge(holiday_tmp2, on="정류소ID", how="left", copy=False).rename(columns = {"전체승하차건수" : "공휴일전체승하차건수"})

print(holiday_final.shape)
holiday_final.head()

(515, 9)


정류소ID  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도
0  200000006 0.789157 0.074057 0.136786  885.335606          7          0          0 6002.522727
1  200000008 0.611576 0.000643 0.387781  172.777778          0          0          0  634.666667
2  200000021 0.526810 0.038874 0.434316   87.764706          0          0          0  521.294118
3  200000036 0.352423 0.024229 0.623348  100.888889          0          0          0  399.000000
4  200000047 0.202474 0.007174 0.790351  137.177778          0          0          4 1663.419192

### (4) Data Merge with Bus Data 

In [65]:
busdf2 = busdf.copy()

In [66]:
busdf2 = busdf2.merge(weekday_final, on="정류소ID", how="left")
busdf2 = busdf2.merge(weekend_final, on="정류소ID", how="left")
busdf2 = busdf2.merge(holiday_final, on="정류소ID", how="left")

# 공휴일 운행 안 하는 버스 0로 채워주기 
busdf2 = busdf2.fillna(0)

In [67]:
print(busdf2.shape)
busdf2.head(3)

(516, 71)


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667
2  200000036               풍림아파트입구 1.000000 0.000000 0.000000    1.000000 0.000000 126.995257 37.297929       0      1       2  10.415812 0.912402  0.673753 0.087598 0.064686  0.738438 0.387562 0.037209 0.575229  73.186301  66.775342  6.410959  99.109589                   0               0             0             1             0               0 172.295890       0       0       0    17.833333    17.833333   8.000000 0.390197 0.039952 0.569850 195.915663    1.000000    0.000000 133.750000         0         0         0  674.184739  8.000000  10.500000 0.381641 0.028005 0.590354  123.605769    1.000000    0.000000 101.904762         0         0         0  531.663462 10.500000 0.352423 0.024229 0.623348  100.888889   0.000000   0.000000   0.000000  399.000000

In [68]:
busdf = busdf2.copy()

### (5) 기상 정보 반영 
* 일자별 기상 데이터 : **[기상자료개방포털](https://data.kma.go.kr/data/grnd/selectAsosRltmList.do?pgmNo=36)** > 종관기상관측 (ASOS)
* 일자별 미세먼지 데이터 : **[에어코리아](https://www.airkorea.or.kr/web/sidoQualityCompare?itemCode=10008&pMENU_NO=102)** > 시도별 대기정보 (PM2.5 & PM10)

#### 일자별 기상 데이터 

In [69]:
weather = pd.read_csv(current_path+'/data/suwon_weather.csv', encoding="CP949")

print(weather.shape)
weather.head()

(8784, 37)


지점 지점명                일시    기온(°C)  기온 QC플래그  강수량(mm)  강수량 QC플래그  풍속(m/s)  풍속 QC플래그   풍향(16방위)  풍향 QC플래그  습도(%)  습도 QC플래그  증기압(hPa)  이슬점온도(°C)   현지기압(hPa)  현지기압 QC플래그   해면기압(hPa)  해면기압 QC플래그  일조(hr)  일조 QC플래그  일사(MJ/m2)  적설(cm)  3시간신적설(cm)  전운량(10분위)  중하층운량(10분위) 운형(운형약어)  최저운고(100m )  시정(10m)  지면상태(지면상태코드)  현상번호(국내식)  지면온도(°C)  지면온도 QC플래그  5cm 지중온도(°C)  10cm 지중온도(°C)  20cm 지중온도(°C)  30cm 지중온도(°C)
0  119  수원  2020-01-01 00:00 -6.000000       nan      nan   9.000000 1.500000       nan 160.000000       nan     64       nan  2.500000 -11.700000 1029.100000         nan 1034.300000         nan     nan  9.000000        nan     nan         nan   9.000000     9.000000       Sc    14.000000     2000           nan        nan -3.700000         nan           nan            nan            nan            nan
1  119  수원  2020-01-01 01:00 -6.300000       nan      nan   9.000000 2.400000       nan 160.000000       nan     74       nan  2.800000 -10.100000 1028.600000         nan 1033.800000         nan     nan  9.000000        nan     nan         nan   9.000000     9.000000       Sc    10.000000     1919           nan   5.000000 -3.800000         nan           nan            nan            nan            nan
2  119  수원  2020-01-01 02:00 -6.200000       nan      nan   9.000000 1.600000       nan 140.000000       nan     70       nan  2.700000 -10.700000 1028.200000         nan 1033.400000         nan     nan  9.000000        nan     nan         nan   6.000000     6.000000       Sc    10.000000     1955           nan   5.000000 -4.200000         nan           nan            nan            nan            nan
3  119  수원  2020-01-01 03:00 -5.800000       nan 0.000000   9.000000 1.600000       nan 160.000000       nan     65       nan  2.600000 -11.300000 1028.300000         nan 1033.500000         nan     nan  9.000000        nan     nan         nan   7.000000     7.000000       Sc     8.000000     2000           nan        nan -4.100000         nan           nan            nan            nan            nan
4  119  수원  2020-01-01 04:00 -5.400000       nan      nan   9.000000 1.300000       nan 160.000000       nan     64       nan  2.600000 -11.100000 1028.300000         nan 1033.500000         nan     nan  9.000000        nan     nan         nan   9.000000     9.000000       Sc     5.000000     2000           nan   5.000000 -3.500000         nan           nan            nan            nan            nan

In [70]:
# 결측값 채우기 
weather = weather.fillna(0)

# 일자 data type 바꿔주기 
tqdm.pandas()
weather["일시"] = weather["일시"].progress_apply(lambda x: pd.to_datetime(str(x), format='%Y%m%d %H:%M'))
weather["date"] = weather["일시"].progress_apply(lambda x : x.strftime('%Y%m%d'))

# 체감온도 : 13.12 + 0.6215T - 11.37V^0.16 + 0.3965V^0.16T (T : 기온(°C), V : 풍속(km/h))
weather["체감온도"] = weather.progress_apply(lambda x : 13.12 + 0.6215 * x['기온(°C)'] - 11.37 * (x['풍속(m/s)'] * 3.6)**0.16 + 0.3965 * (x['풍속(m/s)'] * 3.6)**0.16 * x['기온(°C)'], axis = 1)

# column drop 
weather = weather.drop(["지점", "지점명", '일시'], axis=1)

100%|██████████| 8784/8784 [00:00<00:00, 27343.34it/s]


In [71]:
# 최저기온 & 최고기온 
weather_tmp = weather.groupby(["date"]).agg({
    '기온(°C)' : [('최고기온', np.max), ('최저기온', np.min)], 
    '강수량(mm)' : [('최고강수량', np.max)], 
    '체감온도' : [("최고체감온도" , np.max), ("최저체감온도" , np.min)]
}).reset_index()

weather_tmp.columns = weather_tmp.columns.get_level_values(level=1)
weather_tmp = weather_tmp.rename(columns = {'' : "일자"})

weather_tmp["일자"] = weather_tmp["일자"].progress_apply(lambda x: pd.to_datetime(str(x), format='%Y%m%d'))

100%|██████████| 366/366 [00:00<00:00, 3577.15it/s]


In [72]:
print(weather_tmp.shape)
weather_tmp.head()

(366, 6)


일자     최고기온      최저기온    최고강수량    최고체감온도     최저체감온도
0 2020-01-01 0.200000 -6.300000 0.000000  2.332181 -10.377334
1 2020-01-02 3.200000 -0.300000 0.000000  4.231197  -0.278337
2 2020-01-03 5.200000 -3.900000 0.000000 11.814850  -3.620122
3 2020-01-04 7.400000 -4.300000 0.000000  5.136829  -4.504902
4 2020-01-05 6.200000 -5.500000 0.000000  7.951185  -6.931294

In [73]:
final = final.merge(weather_tmp, on="일자", how="left")
final["전체승하차건수"] = final.progress_apply(lambda x : x["전체 승차 건수"] + x["전체 하차 건수"], axis=1)
final[["log전체승하차건수"]] = np.log1p(final[["전체승하차건수"]])

100%|██████████| 1326103/1326103 [01:38<00:00, 13486.24it/s]


In [74]:
# 일자별로 각 승하차 정류소 다 더한 데이터 
busnum = final.groupby(["일자", "정류소ID"]).sum().reset_index()[["일자","정류소ID","전체승하차건수"]]
busnum = busnum.merge(weather_tmp, on="일자", how="left")

In [75]:
# 정류소 별 일자 데이터로 상관계수 구하기 
busdf["강수량상관관계"] , busdf["온도상관관계"] = .1, .1

for i in tqdm(range(len(busdf))) : 
    busid = busdf.정류소ID.iloc[i]
    corrmatrix = busnum[busnum["정류소ID"] == busid][['전체승하차건수', '최고강수량', '최고체감온도']].corr()
    busdf["강수량상관관계"].iloc[i] , busdf["온도상관관계"].iloc[i] = corrmatrix.iloc[0][1], corrmatrix.iloc[0][2]

100%|██████████| 516/516 [00:02<00:00, 241.50it/s]


#### 미세먼지 데이터 

In [76]:
dust_loc = df_11.drop_duplicates(["측정소", "lon", "lat"], keep="first").reset_index()
dust_loc = dust_loc[["측정소", "lon", "lat"]]

# 에어코리아 데이터에 없는 동수원 측정소 삭제 
dust_loc = dust_loc[dust_loc["측정소"] != "동수원"].reset_index(drop=True)
locs = list(dust_loc["측정소"])

In [77]:
def dist(bus, dust, dong):
    
    ''' 
    측정소랑 버스정류장 사이의 거리 구하는 함수
    dong: '동이름' 으로 설정하기 
    '''
    
    bus[dong+"거리"] = 0
    end = (dust[dust['측정소'] == dong]['lon'], dust[dust['측정소']== dong]['lat'])
    
    for i in tqdm(range(len(bus))):
        start_lon, start_lat = bus["lon"].iloc[i], bus["lat"].iloc[i]
        start=(start_lon,start_lat)
        km=haversine(start,end,unit="km")
        bus[dong+"거리"].iloc[i]=km

In [78]:
# 각 동의 측정소와 버스정류장 사이의 거리 구하기
for i in dust_loc['측정소'].unique():
    dist(busdf, dust_loc, i)

100%|██████████| 516/516 [00:00<00:00, 3157.71it/s]


In [79]:
def dust(month, dust_type="dust", nd=True) : 

    '''
    에어코리아 일별 미세먼지 정보 크롤링 
    '''
    
    if dust_type == "dust": 
        code = 10007 # dust (PM10)
    else : 
        code = 10008 # microdust (PM2.5)

        
    # 11월 & 12월 
    i, cookie = 0, ''
    if nd : 
        i = 0 
        cookie = 'AnrW81RXFCe9NzGRc7yB7mD7GnEeCqDbgJOuaWXoArKZx2vrJsaFpH1RGRWiT7xk'
        url = f"https://www.airkorea.or.kr/web/sidoAirInfo/sidoAirInfoDay30ByLast?itemCode={code}&areaCode=031&tDate=2020-{month}-01&monthDay=31&tYear=2020&tDt={month}"
    
    else : 
        i = 2
        cookie = 'PfGEdNJPn8pm55AanuOZv2QehvTBsvhi9ZVjVbGuGMZPehjxJjlRRTkmXSN5QEFd'
        url = f"https://www.airkorea.or.kr/web/sidoAirInfo/sidoAirInfoDay30?areaCode=031&monthDay=31&itemCode={code}&ymd=2020-{month}-31&tDate=2020-{month}-01"
            
        
    payload={}
        
    headers = {
      'Cookie': f'JSESSIONID={cookie}.airwas2_servlet_newairkorea2; WMONID=ZEWH_QYKHxh'
    }              
        
    response = requests.request("GET", url, headers=headers, data=payload)
    html = response.text 
    soup = BeautifulSoup(html, 'html.parser')
    
    
    place_list = [] 
    places = soup.select("tr")  
    for place in places : 
        if nd : 
            place = re.sub(r'\n', '', place.text)
        else : 
            place = re.sub(r'\n', ' ', place.text)
        place_list.append(place)
        
    dust_list = [] 
    for pl in place_list : 
        dust_list.append(pl.split())
        
    dust_dict = dict() 
    for dst in dust_list : 
        if dst[i] in locs : 
            dust_dict[dst[i]] = dst[(i+1):]
            
    # 측정되지 않은 날짜 처리 
    for loc, dusts in dust_dict.items() : 
        if len(dusts) != 31 : 
            dusttt = [] 
            for dust in dusts : 
                if '-' not in dust : 
                    dusttt.append(dust)
                else : 
                    num = dust.find('-')
                    l = len(dust)
                    dust = re.sub(r'-', '', dust)                        
                    dusttt.extend([dust] * (l-num+1)) 
                    
            dust_dict[loc] = dusttt
            
    dust_dict = pd.DataFrame(dust_dict)
    
    # 월별 날짜에 맞게 dataframe 생성 
    if int(month) in [1,3,5,7,8,10,12] : 
        date_range = pd.date_range(f'2020-{month}-01', f'2020-{month}-31')
    elif int(month) in [4,6,9,11] : 
        dust_dict = dust_dict[:30]
        date_range = pd.date_range(f'2020-{month}-01', f'2020-{month}-30')
    else : 
        dust_dict = dust_dict[:29]
        date_range = pd.date_range(f'2020-{month}-01', f'2020-{month}-29')
        
    dust_dict.index = date_range
    
    return dust_dict

In [80]:
# 미세먼지
dustdf = pd.concat([dust('01'), dust('02'), dust('03'), dust('04'), dust('05'), dust('06'), 
                    dust('07'), dust('08'), dust('09'), dust('10'), dust('11', nd=False), dust('12', nd=False)] , axis=0)

# 초미세먼지 
microdustdf = pd.concat([dust('01', dust_type="micro"), dust('02', dust_type="micro"), dust('03', dust_type="micro"), 
                         dust('04', dust_type="micro"), dust('05', dust_type="micro"), dust('06', dust_type="micro"), 
                         dust('07', dust_type="micro"), dust('08', dust_type="micro"), dust('09', dust_type="micro"), 
                         dust('10', dust_type="micro"), dust('11', dust_type="micro", nd=False), dust('12', dust_type="micro", nd=False)] , axis=0)

In [81]:
# data save 
# with open(os.path.join(current_path, 'data', 'dustdf.pickle'), 'wb') as f:
#     pickle.dump(dustdf, f)
    
# with open(os.path.join(current_path, 'data', 'microdustdf.pickle'), 'wb') as f:
#     pickle.dump(microdustdf, f)

In [82]:
# 오류가 생긴다면, 주석처리를 제외하고 pickle 파일을 불러와 주세요! 

# with open(os.path.join(current_path, 'data', 'dustdf.pickle'), 'r') as f:
#     dustdf = pickle.load(f)
    
# with open(os.path.join(current_path, 'data', 'microdustdf.pickle'), 'r') as f:
#     microdustdf = pickle.load(f)

In [83]:
busnum = busnum.merge(busdf[['정류소ID', '고색동거리', '광교동거리', '신풍동거리', '영통동거리', '인계동거리', '천천동거리', '호매실동거리']], on="정류소ID", how="left")

In [84]:
busnum["미세먼지"], busnum["초미세먼지"] = 0, 0 
locdic = {0 : '고색동', 1 : '광교동', 2 : '신풍동', 3 : '영통동', 4 : '인계동', 5 : '천천동', 6 : '호매실동'}

for i in tqdm(range(len(busnum))):
    idx = np.argmin(busnum[['고색동거리', '광교동거리', '신풍동거리', '영통동거리', '인계동거리', '천천동거리', '호매실동거리']].iloc[i])  
    busnum["미세먼지"].iloc[i]=dustdf.loc[busnum.iloc[i]["일자"]][locdic[idx]]
    busnum["초미세먼지"].iloc[i]=microdustdf.loc[busnum.iloc[i]["일자"]][locdic[idx]]
    

100%|██████████| 185554/185554 [21:15<00:00, 145.48it/s]


In [85]:
busnum = busnum.replace({'미세먼지': '-'}, {'미세먼지': np.mean([int(a) for a in list(dustdf.loc["2020-12-13"]) if a != '-'])})

busnum["미세먼지"] = busnum["미세먼지"].astype('int')
busnum["초미세먼지"] = busnum["초미세먼지"].astype('int')

In [86]:
busdf["미세먼지상관관계"] , busdf["초미세먼지상관관계"] = .1, .1

for i in tqdm(range(len(busdf))) : 
    busid = busdf.정류소ID.iloc[i]
    corrmatrix = busnum[busnum["정류소ID"] == busid][['전체승하차건수', '미세먼지', '초미세먼지']].corr()
    busdf["미세먼지상관관계"].iloc[i] , busdf["초미세먼지상관관계"].iloc[i] = corrmatrix.iloc[0][1], corrmatrix.iloc[0][2]

100%|██████████| 516/516 [00:02<00:00, 243.24it/s]


## 2-3. bus data NLP 

In [87]:
def clean_text(texts):
    station = re.sub(r'[@%\\*=()/~#&\+á?\xc3\xa1\-\|\:\;\!\-\,\.\_\~\$\'\"\[\]]', '', texts) #remove punctuation
    station = re.sub(r'[a-zA-Z]', '', station)    # remove English
    station = re.sub(r'\d+', '', station)         # remove number
    station = re.sub(r'\s+', '', station)         # remove extra space
    station = re.sub(r'\s+', '', station)         # remove spaces
    station = re.sub(r'㈜', '', station)           # remove ㈜
    return station

In [88]:
def place() : 
    '''
    수원시 홈페이지 > 수원소개 > 도시 사용설명서 장소 크롤링 
    '''
    
    url = "https://www.suwon.go.kr/web/board/BD_board.list.do?bbsCd=1290"

    payload={}
    headers = {
      'Cookie': 'JSESSIONID=aYS7VehufcZAzxxeoLRtCYxGLhIQgl486z5LGalyOrho1lEUJouvZ3lKS1OB4aIk.WAS2_servlet_engine1'
    }

    response = requests.request("GET", url, headers=headers, data=payload)
    html = response.text 
    soup = BeautifulSoup(html, 'html.parser')
    
    places = soup.select("div.yearPlanDetail")
    place_list = [] 
    
    for place in places : 
        pl = place.select("ul li a")
        for p in pl : 
            p = re.findall(r"\"[A-Za-z0-9가-힣\s]+", p.text)[0][1:]
            place_list.append(p)
    
    return place_list

In [89]:
# 516개의 버스 정류장 데이터 
bus_station = pd.DataFrame(np.unique(busdf['정류장명']), columns = ['station'])
bus_station["clean_station"] = bus_station['station'].apply(lambda x: clean_text(x))

# 학습을 위한 전체 버스 정류장 데이터 
bus_station2 = pd.DataFrame(np.unique(df_01['정류장명']), columns = ['station'])

# 수원시 관광명소 데이터   
place_list = pd.DataFrame(place(), columns=["station"])

# 학습 데이터 만들기 : 전체 버스 정류장 데이터 (1179) + 수원시 관광명소 데이터 (30)
clean_station2 = pd.concat((bus_station2, place_list), axis=0)
clean_station2['station'] = clean_station2['station'].apply(lambda x: clean_text(x))

In [90]:
# tokenizing 
okt = Okt()
%time  clean_station2 = pd.DataFrame(clean_station2['station'].apply(lambda x: okt.morphs(x)))

%time  bus_station['station_tokens'] = bus_station['clean_station'].apply(lambda x: okt.morphs(x))

CPU times: user 10.1 s, sys: 170 ms, total: 10.3 s
Wall time: 10.8 s
CPU times: user 1.07 s, sys: 4.66 ms, total: 1.07 s
Wall time: 1.12 s


In [91]:
def make_token_list(tokens):
    token_list = [t for s in tokens for t in s]    
    return token_list

tokens = make_token_list(clean_station2['station'])

In [92]:
# corpus 
corpus = Corpus()
corpus.fit(clean_station2['station'], window=5)

# modeling
glove = Glove(no_components=128, learning_rate=0.01, random_state = 2021)    
glove.fit(corpus.matrix, epochs=50, no_threads=4, verbose=False)    
glove.add_dictionary(corpus.dictionary)

In [93]:
word_dict = {}
for word in  glove.dictionary.keys():
    word_dict[word] = glove.word_vectors[glove.dictionary[word]]

In [94]:
def bus_embedding(tokens, embedding_dim=128):
 
    size = len(tokens)
    matrix = np.zeros((size, embedding_dim))
    word_table = word_dict     # glove word_dict

    for i, token in enumerate(tokens):
        vector = np.array([
            word_table[t] for t in token
            if t in word_table
        ])

        if vector.size != 0:
            final_vector = np.mean(vector, axis=0)
            matrix[i] = final_vector

    return matrix

In [95]:
bus_emb = bus_embedding(bus_station["station_tokens"])

In [96]:
k = 10
kmeans = KMeans(n_clusters=k, random_state=2021)
y_pred = kmeans.fit_predict(bus_emb)

In [97]:
bus_station["nlp_cluster"] = y_pred

In [98]:
busdf = busdf.merge(bus_station.drop(["clean_station"], axis=1), left_on="정류장명", right_on="station", how="left")
busdf = busdf.drop(["station", "station_tokens"], axis=1)

In [99]:
print(busdf.shape)
busdf.head(3)

(516, 83)


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도   강수량상관관계   온도상관관계    고색동거리    광교동거리    신풍동거리    영통동거리    인계동거리    천천동거리   호매실동거리  미세먼지상관관계  초미세먼지상관관계  nlp_cluster
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727 -0.194810 0.402356 6.709683 4.612747 2.373598 4.643121 2.437335 6.041080 8.369192  0.023169  -0.123956            8
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667 -0.206834 0.225646 6.849480 4.915871 2.548656 5.232781 3.036157 5.924470 8.365801  0.040863  -0.030205            8
2  200000036               풍림아파트입구 1.000000 0.000000 0.000000    1.000000 0.000000 126.995257 37.297929       0      1       2  10.415812 0.912402  0.673753 0.087598 0.064686  0.738438 0.387562 0.037209 0.575229  73.186301  66.775342  6.410959  99.109589                   0               0             0             1             0               0 172.295890       0       0       0    17.833333    17.833333   8.000000 0.390197 0.039952 0.569850 195.915663    1.000000    0.000000 133.750000         0         0         0  674.184739  8.000000  10.500000 0.381641 0.028005 0.590354  123.605769    1.000000    0.000000 101.904762         0         0         0  531.663462 10.500000 0.352423 0.024229 0.623348  100.888889   0.000000   0.000000   0.000000  399.000000 -0.013023 0.087172 3.702636 8.391093 1.935795 7.598513 4.372229 2.244175 4.754531  0.058419   0.056768            3

# 3. 미세먼지 데이터 

In [100]:
# 호매실동 빈값 3개 채워넣기
df_11.iloc[6,3:9]=df_11.iloc[102,3:9]
df_11.iloc[14,3:9]=df_11.iloc[110,3:9]
df_11.iloc[22,3:9]=df_11.iloc[118,3:9]

# 데이터 형변환
df_11[["미세먼지(㎍/㎥)","초미세먼지(㎍/㎥)","오존(ppm)","이산화질소(ppm)","아황산가스(ppm)","일산화탄소(ppm)"]]=df_11[["미세먼지(㎍/㎥)","초미세먼지(㎍/㎥)","오존(ppm)","이산화질소(ppm)","아황산가스(ppm)","일산화탄소(ppm)"]].astype(float)

# 2019년, 2020년 데이터 평균
df_dust = df_11.groupby(df_11["측정소"]).mean().reset_index()

In [101]:
def dist(bus, dust, dong):
    
    ''' 
    측정소랑 버스정류장 사이의 거리 구하는 함수
    dong: '동이름' 으로 설정하기 
    '''
    
    bus[dong+"거리"] = 0
    end = (dust[dust['측정소'] == dong]['lon'], dust[dust['측정소']== dong]['lat'])
    
    for i in range(len(bus)):
        start_lon, start_lat = bus["lon"].iloc[i], bus["lat"].iloc[i]
        start=(start_lon,start_lat)
        km=haversine(start,end,unit="km")
        bus[dong+"거리"].iloc[i]=km

In [102]:
# 각 동의 측정소와 버스정류장 사이의 거리 구하기
for i in df_dust['측정소'].unique():
    dist(busdf, df_dust, i)

In [103]:
# 가장 가까운 측정소의 미세먼지 값 넣기
busdf["미세먼지(㎍/㎥)"], busdf["초미세먼지(㎍/㎥)"], busdf["오존(ppm)"], busdf["이산화질소(ppm)"], busdf["아황산가스(ppm)"], busdf["일산화탄소(ppm)"] = 0, 0, 0, 0, 0, 0

for i in range(len(busdf)):
    idx = np.argmin(busdf[['고색동거리', '광교동거리', '동수원거리', '신풍동거리', '영통동거리', '인계동거리', '천천동거리', '호매실동거리']].iloc[i])
    
    busdf["미세먼지(㎍/㎥)"].iloc[i]=df_dust.iloc[idx]["미세먼지(㎍/㎥)"]
    busdf["초미세먼지(㎍/㎥)"].iloc[i]=df_dust.iloc[idx]["초미세먼지(㎍/㎥)"]
    busdf["오존(ppm)"].iloc[i]=df_dust.iloc[idx]["오존(ppm)"]
    busdf["이산화질소(ppm)"].iloc[i]=df_dust.iloc[idx]["이산화질소(ppm)"]
    busdf["아황산가스(ppm)"].iloc[i]=df_dust.iloc[idx]["아황산가스(ppm)"]
    busdf["일산화탄소(ppm)"].iloc[i]=df_dust.iloc[idx]["일산화탄소(ppm)"]

In [104]:
print(busdf.shape)
busdf.head(3)

(516, 90)


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도   강수량상관관계   온도상관관계    고색동거리    광교동거리    신풍동거리    영통동거리    인계동거리    천천동거리   호매실동거리  미세먼지상관관계  초미세먼지상관관계  nlp_cluster    동수원거리  미세먼지(㎍/㎥)  초미세먼지(㎍/㎥)  오존(ppm)  이산화질소(ppm)  아황산가스(ppm)  일산화탄소(ppm)
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727 -0.194810 0.402356 6.709683 4.612747 2.373598 4.643121 2.437335 6.041080 8.369192  0.023169  -0.123956            8 1.562486  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667 -0.206834 0.225646 6.849480 4.915871 2.548656 5.232781 3.036157 5.924470 8.365801  0.040863  -0.030205            8 2.178657  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167
2  200000036               풍림아파트입구 1.000000 0.000000 0.000000    1.000000 0.000000 126.995257 37.297929       0      1       2  10.415812 0.912402  0.673753 0.087598 0.064686  0.738438 0.387562 0.037209 0.575229  73.186301  66.775342  6.410959  99.109589                   0               0             0             1             0               0 172.295890       0       0       0    17.833333    17.833333   8.000000 0.390197 0.039952 0.569850 195.915663    1.000000    0.000000 133.750000         0         0         0  674.184739  8.000000  10.500000 0.381641 0.028005 0.590354  123.605769    1.000000    0.000000 101.904762         0         0         0  531.663462 10.500000 0.352423 0.024229 0.623348  100.888889   0.000000   0.000000   0.000000  399.000000 -0.013023 0.087172 3.702636 8.391093 1.935795 7.598513 4.372229 2.244175 4.754531  0.058419   0.056768            3 4.166880  39.458333   23.125000 0.027917    0.024917    0.002958    0.562500

# 4. 지하철역 데이터 

## 4-1. 500m내지하철역갯수

In [105]:
def dist2(bus, station):
    
    ''' 
    지하철역랑 버스정류장 사이의 거리 구하는 함수
    station: '역사이름'으로 설정하기 
    '''  
    
    bus[station] = 0
    end = (df_08[df_08['역사명']==station]['lon'] , df_08[df_08['역사명']==station]['lat'])
    
    for i in range(len(bus)):
        start_lon, start_lat = bus["lon"].iloc[i], bus["lat"].iloc[i]
        start=(start_lon,start_lat)
        km = haversine(start, end, unit = 'km')
        bus[station].iloc[i] = km

In [106]:
for i in df_08['역사명'].unique():
    dist2(busdf, i)

In [107]:
busdf.head(2)

정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도   강수량상관관계   온도상관관계    고색동거리    광교동거리    신풍동거리    영통동거리    인계동거리    천천동거리   호매실동거리  미세먼지상관관계  초미세먼지상관관계  nlp_cluster    동수원거리  미세먼지(㎍/㎥)  초미세먼지(㎍/㎥)  오존(ppm)  이산화질소(ppm)  아황산가스(ppm)  일산화탄소(ppm)    성균관대역      화서역  수원(분당)역      세류역  \
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727 -0.194810 0.402356 6.709683 4.612747 2.373598 4.643121 2.437335 6.041080 8.369192  0.023169  -0.123956            8 1.562486  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167 6.516358 4.562602 3.999946 4.130102   
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667 -0.206834 0.225646 6.849480 4.915871 2.548656 5.232781 3.036157 5.924470 8.365801  0.040863  -0.030205            8 2.178657  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167 6.346367 4.555895 4.220473 4.609356   

       청명역      영통역      망포역    매탄권선역    수원시청역      매교역      고색역     오목천역  광교중앙(아주대)역  광교(경기대)역      수원역  
0 6.135732 5.677920 4.776889 3.426342 2.553497 2.774218 6.679065 8.253950    2.564164  1.675973 3.994276  
1 6.591810 6.192714 5.364495 4.054839 3.165719 3.202148 6.844825 8.379205    2.974036  1.921543 4.220959

In [108]:
# 지하철역 500m 안에 있으면 1 아니면 0
for station in df_08['역사명'].unique() : 
    busdf[station] = busdf[station].apply(lambda x : 1 if x <= 0.5 else 0)
    
busdf["500m내지하철역갯수"] = busdf[df_08['역사명'].unique()].apply(sum, axis=1)

In [109]:
busdf["500m내지하철역갯수"].value_counts()

0    386
1    118
2     12
Name: 500m내지하철역갯수, dtype: int64

## 4-2. 지하철 역 평균 이용객 수

In [110]:
# 숫자형으로 변환
df_09["모든요일(2017)"]=df_09["모든요일(2017)"].str.replace(",", "").astype('int64')
df_09["모든요일(2018)"]=df_09["모든요일(2018)"].str.replace(",", "").astype('int64')
df_09["모든요일(2019)"]=df_09["모든요일(2019)"].str.replace(",", "").astype('int64')

In [111]:
df_이용객=df_09.groupby("역명").mean().reset_index()
df_이용객["평균지하철이용객"]=(df_이용객["모든요일(2017)"]+df_이용객["모든요일(2018)"]+df_이용객["모든요일(2019)"])/3

# 없는 정류장 빼주기
busdf=busdf.drop(["고색역",'오목천역','광교중앙(아주대)역','광교(경기대)역'],axis=1)

# 수원을 수원역으로 바꿔줌
df_이용객["역명"]=df_이용객["역명"].replace("수원","수원역")

for i in range(len(busdf)):
    for station in df_이용객['역명'].unique():
        if busdf[station][i]<= 0.5:
            busdf[station][i]=df_이용객[df_이용객["역명"]==station]["평균지하철이용객"]
        else:
            busdf[station][i]= 0   
            
busdf["지하철이용객"] = busdf[df_이용객['역명'].unique()].apply(sum, axis=1)

# 역 정보 삭제 
busdf = busdf.drop(list(df_이용객['역명'].unique()), axis=1)

In [112]:
print(busdf.shape)
busdf.head(3)

(516, 92)


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도   강수량상관관계   온도상관관계    고색동거리    광교동거리    신풍동거리    영통동거리    인계동거리    천천동거리   호매실동거리  미세먼지상관관계  초미세먼지상관관계  nlp_cluster    동수원거리  미세먼지(㎍/㎥)  초미세먼지(㎍/㎥)  오존(ppm)  이산화질소(ppm)  아황산가스(ppm)  일산화탄소(ppm)  500m내지하철역갯수   지하철이용객
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727 -0.194810 0.402356 6.709683 4.612747 2.373598 4.643121 2.437335 6.041080 8.369192  0.023169  -0.123956            8 1.562486  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667 -0.206834 0.225646 6.849480 4.915871 2.548656 5.232781 3.036157 5.924470 8.365801  0.040863  -0.030205            8 2.178657  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133
2  200000036               풍림아파트입구 1.000000 0.000000 0.000000    1.000000 0.000000 126.995257 37.297929       0      1       2  10.415812 0.912402  0.673753 0.087598 0.064686  0.738438 0.387562 0.037209 0.575229  73.186301  66.775342  6.410959  99.109589                   0               0             0             1             0               0 172.295890       0       0       0    17.833333    17.833333   8.000000 0.390197 0.039952 0.569850 195.915663    1.000000    0.000000 133.750000         0         0         0  674.184739  8.000000  10.500000 0.381641 0.028005 0.590354  123.605769    1.000000    0.000000 101.904762         0         0         0  531.663462 10.500000 0.352423 0.024229 0.623348  100.888889   0.000000   0.000000   0.000000  399.000000 -0.013023 0.087172 3.702636 8.391093 1.935795 7.598513 4.372229 2.244175 4.754531  0.058419   0.056768            3 4.166880  39.458333   23.125000 0.027917    0.024917    0.002958    0.562500            0  3954133

# 5. 계절별 미세먼지 

In [113]:
df_11["년"] = df_11.측정월.str.split(".").str[0]
df_11["월"] = df_11.측정월.str.split(".").str[1]

df_11['계절'] = ["겨울" if s in ("1월", "2월", "12월") 
               else "봄" if s in ("3월", "4월", "5월")   
               else "여름"  if s in ("6월","7월","8월") 
               else "가을" for s in df_11["월"]]

df_dust2 = df_11.groupby(["측정소","계절"]).mean().reset_index()

In [114]:
busdf["미세_봄"], busdf["미세_여름"], busdf["미세_가을"], busdf["미세_겨울"] = 0, 0, 0, 0
busdf["초미세_봄"], busdf["초미세_여름"], busdf["초미세_가을"], busdf["초미세_겨울"] = 0, 0, 0, 0

In [115]:
for i in range(len(busdf)):
    place = busdf[['고색동거리', '광교동거리', '동수원거리', '신풍동거리', '영통동거리', '인계동거리', '천천동거리', '호매실동거리']].iloc[i].idxmin()[:-2]

    busdf["미세_봄"].iloc[i] = df_dust2[(df_dust2["측정소"] == place) & (df_dust2["계절"] == "봄")]["미세먼지(㎍/㎥)"].values
    busdf["미세_여름"].iloc[i] = df_dust2[(df_dust2["측정소"] == place) & (df_dust2["계절"] == "여름")]["미세먼지(㎍/㎥)"].values
    busdf["미세_가을"].iloc[i] = df_dust2[(df_dust2["측정소"] == place) & (df_dust2["계절"] == "가을")]["미세먼지(㎍/㎥)"].values
    busdf["미세_겨울"].iloc[i] = df_dust2[(df_dust2["측정소"] == place) & (df_dust2["계절"] == "겨울")]["미세먼지(㎍/㎥)"].values

    busdf["초미세_봄"].iloc[i] = df_dust2[(df_dust2["측정소"] == place) & (df_dust2["계절"] == "봄")]["초미세먼지(㎍/㎥)"].values
    busdf["초미세_여름"].iloc[i] = df_dust2[(df_dust2["측정소"] == place) & (df_dust2["계절"] == "여름")]["초미세먼지(㎍/㎥)"].values
    busdf["초미세_가을"].iloc[i] = df_dust2[(df_dust2["측정소"] == place) & (df_dust2["계절"] == "가을")]["초미세먼지(㎍/㎥)"].values
    busdf["초미세_겨울"].iloc[i] = df_dust2[(df_dust2["측정소"] == place) & (df_dust2["계절"] == "겨울")]["초미세먼지(㎍/㎥)"].values

In [116]:
# 미세먼지 측정소 거리 삭제 
busdf  = busdf.drop(list(busdf.columns[busdf.columns.str.contains("거리")]), axis=1)

In [117]:
print(busdf.shape)
busdf.head(3)

(516, 92)


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도   강수량상관관계   온도상관관계  미세먼지상관관계  초미세먼지상관관계  nlp_cluster  미세먼지(㎍/㎥)  초미세먼지(㎍/㎥)  오존(ppm)  이산화질소(ppm)  아황산가스(ppm)  일산화탄소(ppm)  500m내지하철역갯수   지하철이용객      미세_봄     미세_여름     미세_가을     미세_겨울     초미세_봄    초미세_여름    초미세_가을    초미세_겨울
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727 -0.194810 0.402356  0.023169  -0.123956            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667 -0.206834 0.225646  0.040863  -0.030205            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000
2  200000036               풍림아파트입구 1.000000 0.000000 0.000000    1.000000 0.000000 126.995257 37.297929       0      1       2  10.415812 0.912402  0.673753 0.087598 0.064686  0.738438 0.387562 0.037209 0.575229  73.186301  66.775342  6.410959  99.109589                   0               0             0             1             0               0 172.295890       0       0       0    17.833333    17.833333   8.000000 0.390197 0.039952 0.569850 195.915663    1.000000    0.000000 133.750000         0         0         0  674.184739  8.000000  10.500000 0.381641 0.028005 0.590354  123.605769    1.000000    0.000000 101.904762         0         0         0  531.663462 10.500000 0.352423 0.024229 0.623348  100.888889   0.000000   0.000000   0.000000  399.000000 -0.013023 0.087172  0.058419   0.056768            3  39.458333   23.125000 0.027917    0.024917    0.002958    0.562500            0  3954133 48.000000 29.833333 32.333333 47.666667 26.000000 16.333333 17.666667 32.500000

# 6. 실거래가 
* **[국도교통부](http://rtdown.molit.go.kr/)** : 수원시 실거래가 데이터 

## 6-1. 실거래가 데이터 전처리 

### (1) Data Load 

In [118]:
jangan = pd.read_csv(os.path.join(current_path, 'data', 'suwon_jangan.csv'), encoding = 'CP949')
ksun = pd.read_csv(os.path.join(current_path, 'data', 'suwon_ksun.csv'), encoding = 'CP949')
yt = pd.read_csv(os.path.join(current_path, 'data', 'suwon_yt.csv'), encoding = 'CP949')
paldal = pd.read_csv(os.path.join(current_path, 'data', 'suwon_paldal.csv'), encoding = 'CP949')

jangan.shape, ksun.shape, yt.shape, paldal.shape

((5230, 13), (6332, 13), (8798, 13), (2335, 13))

In [119]:
suwon = pd.concat([jangan,ksun,yt,paldal]).reset_index().drop(['index','해제사유발생일'], axis = 1)
print(suwon.shape)
suwon.head(2)

(22695, 12)


시군구     번지   본번  부번        단지명   전용면적(㎡)    계약년월  계약일 거래금액(만원)  층  건축년도             도로명
0  경기도 수원장안구 송죽동  498-3  498   3  대성(A,B,C) 56.160000  202001   19   19,900  1  1989  경수대로939번길 12-6
1  경기도 수원장안구 송죽동  498-3  498   3  대성(A,B,C) 56.880000  202002   24   19,500  4  1989  경수대로939번길 12-6

In [120]:
# 도로명 전처리 
suwon['road'] = suwon['시군구']+suwon['도로명']
road = pd.DataFrame(np.unique(suwon['road']), columns = ['도로명'])

road.to_csv(current_path+'/data/road.csv', index = False, encoding = 'CP949')

### (2) 위경도 변환 
* 주소 좌표 변환 툴 **[Geocoder-Xr](http://www.gisdeveloper.co.kr/?p=4784)** 을 사용해 위경도 정보 추출  

In [121]:
coordinate = pd.read_csv(current_path+'/data/road.shp.csv', encoding = 'CP949')
print(coordinate.shape)
coordinate.head(2)

(578, 5)


No                     도로명         경도        위도   상태
0   1  경기도 수원권선구 고색동고산로6번길 45 126.984874 37.248087  정좌표
1   2      경기도 수원권선구 고색동고색로 8 126.978321 37.247093  정좌표

In [122]:
df_merge = pd.merge(suwon, coordinate, left_on = 'road', right_on = '도로명')

### (3) 파생변수 생성 

In [123]:
# 특수문자 제거 
def clean_text(texts):
    return re.sub('[,]','',texts)

# 제거 후 숫자로 변환
df_merge['거래금액'] = df_merge['거래금액(만원)'].progress_apply(lambda x: int(clean_text(x)))

# 면적당 금액
df_merge['price'] = df_merge['거래금액']/df_merge['전용면적(㎡)']

100%|██████████| 22695/22695 [00:00<00:00, 267866.93it/s]


### (4) 데이터 추출 

In [124]:
# 데이터 형변환
df_merge['계약년월'] = df_merge['계약년월'].progress_apply(lambda x: str(x))
df_merge['계약일'] = df_merge['계약일'].progress_apply(lambda x: '0' + str(x) if x<10 else str(x))

# 계약일자
df_merge['date'] = df_merge['계약년월'] + df_merge['계약일']

df_merge = df_merge[['date', 'road', '건축년도', '전용면적(㎡)', '층', '거래금액', 'price', '경도', '위도']]
# df_merge.to_csv(current_path+'/data/house.csv', encoding = 'CP949', index = False)

100%|██████████| 22695/22695 [00:00<00:00, 337598.92it/s]


## 6-2. 버스정류장 데이터와 합치기 

In [125]:
house = pd.read_csv(current_path+'/data/house.csv', encoding = 'CP949')

house = house.drop_duplicates(['road'], keep = 'last').reset_index() # 가장 최근의 실거래가 이용 
house = house[['road', '건축년도', '전용면적(㎡)', '층', '거래금액', 'price', '경도', '위도']]

In [126]:
def optim_price(station, price):
    for i in tqdm(range(len(station))):
        # 거리 계산
        distance = []
        for j in range(len(price)):
            station_name = tuple(station[['lon','lat']].iloc[i])
            price_name = tuple(price[['경도','위도']].iloc[j])
            distance.append(haversine(station_name, price_name, unit = 'km'))
            
        # 최소
        station['건축년도'][i] = price['건축년도'][np.argmin(distance)]
        station['전용면적(㎡)'][i] = price['전용면적(㎡)'][np.argmin(distance)]
        station['층'][i] = price['층'][np.argmin(distance)]
        station['거래금액'][i] = price['거래금액'][np.argmin(distance)]
        station['면적당 금액'][i] = price['price'][np.argmin(distance)]
        
    return station

In [127]:
busdf['건축년도'], busdf['전용면적(㎡)'], busdf['층'], busdf['거래금액'], busdf['면적당 금액'] = 0, 0, 0, 0, 0
busdf = optim_price(busdf, house)

100%|██████████| 516/516 [09:43<00:00,  1.13s/it]


In [128]:
print(busdf.shape)
busdf.head(3)

(516, 97)


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도   강수량상관관계   온도상관관계  미세먼지상관관계  초미세먼지상관관계  nlp_cluster  미세먼지(㎍/㎥)  초미세먼지(㎍/㎥)  오존(ppm)  이산화질소(ppm)  아황산가스(ppm)  일산화탄소(ppm)  500m내지하철역갯수   지하철이용객      미세_봄     미세_여름     미세_가을     미세_겨울     초미세_봄    초미세_여름    초미세_가을    초미세_겨울  건축년도  \
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727 -0.194810 0.402356  0.023169  -0.123956            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000  2003   
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667 -0.206834 0.225646  0.040863  -0.030205            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000  2003   
2  200000036               풍림아파트입구 1.000000 0.000000 0.000000    1.000000 0.000000 126.995257 37.297929       0      1       2  10.415812 0.912402  0.673753 0.087598 0.064686  0.738438 0.387562 0.037209 0.575229  73.186301  66.775342  6.410959  99.109589                   0               0             0             1             0               0 172.295890       0       0       0    17.833333    17.833333   8.000000 0.390197 0.039952 0.569850 195.915663    1.000000    0.000000 133.750000         0         0         0  674.184739  8.000000  10.500000 0.381641 0.028005 0.590354  123.605769    1.000000    0.000000 101.904762         0         0         0  531.663462 10.500000 0.352423 0.024229 0.623348  100.888889   0.000000   0.000000   0.000000  399.000000 -0.013023 0.087172  0.058419   0.056768            3  39.458333   23.125000 0.027917    0.024917    0.002958    0.562500            0  3954133 48.000000 29.833333 32.333333 47.666667 26.000000 16.333333 17.666667 32.500000  1989   

   전용면적(㎡)

# 7. 교통량, 혼잡시간강도, 혼잡빈도강도 

In [129]:
# 버스정류장에 가까운 교통 링크 filtering 한 데이터 사용 (QGIS)
link = gpd.read_file(current_path+'/data/link_filter.geojson')
link = link.drop_duplicates(["정류장ID"])
link = pd.DataFrame(link[['정류장ID','join_LINK_ID']]).reset_index(drop=True)
link = link.rename(columns = {'join_LINK_ID':'link_id'})

In [130]:
link["road_id"] = None 

for i in range(len(link)):
    a = []
    for j in range(len(df_22)):
        if (link['link_id'][i] == df_22['up_its_id'][j]):
            a.append(df_22['link_id'][j])
        elif(link['link_id'][i] == df_22['dw_its_id'][j]):
            a.append(df_22['link_id'][j])
    link['road_id'][i] = np.unique(a)

In [131]:
# 교통량 데이터 
traffic = link.copy()

df_23_alltime = df_23.groupby(['상세도로망_LinkID']).mean()[['전체_추정교통량','승용차_추정교통량','버스_추정교통량','화물차_추정교통량']]
df_23_alltime = df_23_alltime.reset_index()

# 상행, 하행 평균 
for i in range(len(df_23_alltime)):
    df_23_alltime['상세도로망_LinkID'][i] = str(df_23_alltime['상세도로망_LinkID'][i])[:9]
    
df_23_alltime = df_23_alltime.groupby(['상세도로망_LinkID']).mean()[['전체_추정교통량','승용차_추정교통량','버스_추정교통량','화물차_추정교통량']]
df_23_alltime = df_23_alltime.reset_index()
df_23_alltime['상세도로망_LinkID'] = df_23_alltime['상세도로망_LinkID'].astype('str')

In [132]:
def merge_array(df1, df2, col1, col2, column):
    
    '''
    df1: array column 있는 df, col1: array column name
    df2: array의 원소와 비교해야하는 df, col2: element column name
    column: 넣고싶은 값 column name
    '''
    
    df1['new'] = None
    for i in tqdm(range(len(df1))) :
        a = []
        for j in range(len(df2)):
            if df2[col2][j] in df1[col1][i]:
                a.append(df2[column][j])
        df1['new'][i] = np.mean(a)
        
    return df1

In [133]:
a = ['전체_추정교통량', '승용차_추정교통량', '버스_추정교통량', '화물차_추정교통량']
for i in a:
    traffic = merge_array(traffic, df_23_alltime, 'road_id', '상세도로망_LinkID', i)
    traffic = traffic.rename(columns = {'new':i+'_전체시간'})

100%|██████████| 519/519 [01:24<00:00,  6.17it/s]


In [134]:
# 상행, 하행 평균 내주기
for i in range(len(df_24)):
    df_24['상세도로망_LinkID'][i] = str(df_24['상세도로망_LinkID'][i])[:9]
    
df_24 = df_24.groupby(['상세도로망_LinkID']).mean()[['혼잡빈도강도']]
df_24 = df_24.reset_index()
df_24['상세도로망_LinkID'] = df_24['상세도로망_LinkID'].astype('str')

In [135]:
# 상행, 하행 평균 내주기
for i in range(len(df_25)):
    df_25['상세도로망_LinkID'][i] = str(df_25['상세도로망_LinkID'][i])[:9]
    
df_25 = df_25.groupby(['상세도로망_LinkID']).mean()[['혼잡시간강도']]
df_25 = df_25.reset_index()
df_25['상세도로망_LinkID'] = df_25['상세도로망_LinkID'].astype('str')

In [136]:
# 혼잡시간강도, 혼잡빈도강도 한 df에 merge
df_24_25 = df_24.merge(df_25, on = '상세도로망_LinkID')

In [137]:
a = ['혼잡빈도강도', '혼잡시간강도']
for i in a:
    traffic = merge_array(traffic, df_24_25, 'road_id', '상세도로망_LinkID', i)
    traffic = traffic.rename(columns = {'new':i})
    
# nan 채우기
traffic = traffic.fillna(0)

traffic = traffic.drop(['link_id', 'road_id'], axis = 1)

100%|██████████| 519/519 [01:23<00:00,  6.20it/s]


In [138]:
busdf = busdf.merge(traffic, left_on = '정류소ID', right_on = '정류장ID', copy = False)
busdf = busdf.drop(['정류장ID'], axis = 1)

print(busdf.shape)
busdf.head(2)

(516, 103)


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도   강수량상관관계   온도상관관계  미세먼지상관관계  초미세먼지상관관계  nlp_cluster  미세먼지(㎍/㎥)  초미세먼지(㎍/㎥)  오존(ppm)  이산화질소(ppm)  아황산가스(ppm)  일산화탄소(ppm)  500m내지하철역갯수   지하철이용객      미세_봄     미세_여름     미세_가을     미세_겨울     초미세_봄    초미세_여름    초미세_가을    초미세_겨울  건축년도  \
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727 -0.194810 0.402356  0.023169  -0.123956            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000  2003   
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667 -0.206834 0.225646  0.040863  -0.030205            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000  2003   

   전용면적(㎡)  층   거래금액  면적당 금액  전체_추정교통량_전체시간  승용차_추정교통량_전체시간  버스_추정교통량_전체시간  화물차_추정교통량_전체시간    혼잡빈도강도    혼잡시간강도  
0       75  4  21700     288     486.400000      368.370000       2.760000      115.240000 42.687500 67.075000  
1       75  4  21700     288     156.265714      129.308571       0.402857       26.500000 60.881429 69.982857

# 8. 유동인구 

## 8-1. 출퇴근 유동인구 

In [139]:
# 전체 유동인구
df_all = pd.DataFrame(df_14.groupby(['lon','lat']).mean()[['TMST_00', 'TMST_01', 'TMST_02', 'TMST_03', 'TMST_04', 'TMST_05', 'TMST_06', 'TMST_07', 'TMST_08', 'TMST_09', 'TMST_10', 'TMST_11', 'TMST_12', 'TMST_13', 'TMST_14', 'TMST_15', 'TMST_16', 'TMST_17', 'TMST_18', 'TMST_19', 'TMST_20', 'TMST_21', 'TMST_22', 'TMST_23']].mean(axis=1), columns = ['유동인구_전체'])

# 출근, 퇴근 유동인구
df_on = pd.DataFrame(df_14.groupby(['lon','lat']).mean()[['TMST_07', 'TMST_08', 'TMST_09']].mean(axis=1), columns = ['유동인구_출근'])
df_off = pd.DataFrame(df_14.groupby(['lon','lat']).mean()[['TMST_17', 'TMST_18', 'TMST_19']].mean(axis=1), columns = ['유동인구_퇴근'])

# 데이터 병합
df_new = pd.merge(df_all, df_on, on = ['lon', 'lat'])
df_new = pd.merge(df_new, df_off, on = ['lon', 'lat'])

In [140]:
# 출퇴근 유동인구
df_new['유동인구_출퇴근'] = (df_new['유동인구_출근']+df_new['유동인구_퇴근'])/2

# index 추출
df_new['index'] = df_new.index

# column으로 추출
df_new['lon'] = df_new['index'].apply(lambda x: x[0])
df_new['lat'] = df_new['index'].apply(lambda x: x[1])

# index 전처리
df_new.index = range(0, df_new.shape[0])
df_new = df_new.drop(['index'], axis = 1)

df_new = df_new.sort_values(by = ['lon']).reset_index(drop = True)

In [141]:
# 가장 가까운 격자 찾기 
def find_optim(station, new):
    # 각 정류장에 대해 반복
    for i in tqdm(range(len(station))):
        
        # 계산량을 줄이기 위한 filter
        ## lon
        # sort_lon = new.sort_values(by = ['lon']).reset_index(drop = True)
        idx_lon = bisect_left(new['lon'], station['lon'][i])
        fltr_lon = new[(new['lon']<new.loc[idx_lon, 'lon']+0.001)&(new['lon']>new.loc[idx_lon, 'lon']-0.001)].reset_index(drop = True)
        ## lat
        sort_lat = fltr_lon.sort_values(by = ['lat']).reset_index(drop = True)
        idx_lat = bisect_left(sort_lat['lat'], station['lat'][i])
        fltr_lat = sort_lat[(sort_lat['lat']<sort_lat.loc[idx_lat, 'lat']+0.01)&(sort_lat['lat']>sort_lat.loc[idx_lat, 'lat']-0.01)].reset_index(drop = True)

        # filter된 데이터의 거리 계산
        distance = []
        for j in range(len(fltr_lat)):
            station_name = tuple(station[['lon','lat']].iloc[i])
            fltr_name = tuple(fltr_lat[['lon','lat']].iloc[j])
            distance.append(haversine(station_name, fltr_name, unit = 'km'))
            
        # 가장 가까운 격자의 유동인구
        station['유동인구_전체'][i] = fltr_lat['유동인구_전체'][np.argmin(distance)]
        station['유동인구_출퇴근'][i] = fltr_lat['유동인구_출퇴근'][np.argmin(distance)]
        station['유동인구_출근'][i] = fltr_lat['유동인구_출근'][np.argmin(distance)]
        station['유동인구_퇴근'][i] = fltr_lat['유동인구_퇴근'][np.argmin(distance)]
        
    return station

In [142]:
busdf['유동인구_전체'], busdf['유동인구_출퇴근'], busdf['유동인구_출근'], busdf['유동인구_퇴근'] = 0.1, 0.1, 0.1, 0.1
df_result = find_optim(busdf, df_new)

100%|██████████| 516/516 [02:26<00:00,  3.52it/s]


## 8-2. 성연령별 유동인구 

In [143]:
# 일년치 평균 
pop_df = df_15.drop(['STD_YM'], axis=1).groupby(['lon', 'lat']).mean().reset_index()

busdf['남자10대유동인구'], busdf['남자20대유동인구'], busdf['남자30대유동인구'], busdf['남자40대유동인구'], busdf['남자50대유동인구'], busdf['남자60대유동인구'] = 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 
busdf['여자10대유동인구'], busdf['여자20대유동인구'], busdf['여자30대유동인구'], busdf['여자40대유동인구'], busdf['여자50대유동인구'], busdf['여자60대유동인구'] = 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 

pop_df = pop_df.sort_values(by = ['lon']).reset_index(drop = True)

In [144]:
def population(station, new):
    # 각 정류장에 대해 반복
    for i in tqdm(range(len(station))):
        
        # 계산량을 줄이기 위한 filter
        ## lon
        # sort_lon = new.sort_values(by = ['lon']).reset_index(drop = True)
        idx_lon = bisect_left(new['lon'], station['lon'][i])
        fltr_lon = new[(new['lon']<new.loc[idx_lon, 'lon']+0.001)&(new['lon']>new.loc[idx_lon, 'lon']-0.001)].reset_index(drop = True)
        ## lat
        sort_lat = fltr_lon.sort_values(by = ['lat']).reset_index(drop = True)
        idx_lat = bisect_left(sort_lat['lat'], station['lat'][i])
        fltr_lat = sort_lat[(sort_lat['lat']<sort_lat.loc[idx_lat, 'lat']+0.01)&(sort_lat['lat']>sort_lat.loc[idx_lat, 'lat']-0.01)].reset_index(drop = True)

        # filter된 데이터의 거리 계산
        distance = []
        for j in range(len(fltr_lat)):
            station_name = tuple(station[['lon','lat']].iloc[i])
            fltr_name = tuple(fltr_lat[['lon','lat']].iloc[j])
            distance.append(haversine(station_name, fltr_name, unit = 'km'))
            
        # 가장 가까운 격자의 유동인구
        station['남자10대유동인구'][i] = fltr_lat['MAN_FLOW_POP_CNT_10G'].iloc[np.argmin(distance)]
        station['남자20대유동인구'][i] = fltr_lat['MAN_FLOW_POP_CNT_20G'].iloc[np.argmin(distance)]
        station['남자30대유동인구'][i] = fltr_lat['MAN_FLOW_POP_CNT_30G'].iloc[np.argmin(distance)]
        station['남자40대유동인구'][i] = fltr_lat['MAN_FLOW_POP_CNT_40G'].iloc[np.argmin(distance)]
        station['남자50대유동인구'][i] = fltr_lat['MAN_FLOW_POP_CNT_50G'].iloc[np.argmin(distance)]
        station['남자60대유동인구'][i] = fltr_lat['MAN_FLOW_POP_CNT_60GU'].iloc[np.argmin(distance)]

        station['여자10대유동인구'][i] = fltr_lat['WMAN_FLOW_POP_CNT_10G'].iloc[np.argmin(distance)]
        station['여자20대유동인구'][i] = fltr_lat['WMAN_FLOW_POP_CNT_20G'].iloc[np.argmin(distance)]
        station['여자30대유동인구'][i] = fltr_lat['WMAN_FLOW_POP_CNT_30G'].iloc[np.argmin(distance)]
        station['여자40대유동인구'][i] = fltr_lat['WMAN_FLOW_POP_CNT_40G'].iloc[np.argmin(distance)]
        station['여자50대유동인구'][i] = fltr_lat['WMAN_FLOW_POP_CNT_50G'].iloc[np.argmin(distance)]
        station['여자60대유동인구'][i] = fltr_lat['WMAN_FLOW_POP_CNT_60GU'].iloc[np.argmin(distance)]        
        
    return station

In [145]:
busdf = population(busdf, pop_df)

100%|██████████| 516/516 [02:27<00:00,  3.50it/s]


In [146]:
print(busdf.shape)
busdf.head(2)

(516, 119)


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도   강수량상관관계   온도상관관계  미세먼지상관관계  초미세먼지상관관계  nlp_cluster  미세먼지(㎍/㎥)  초미세먼지(㎍/㎥)  오존(ppm)  이산화질소(ppm)  아황산가스(ppm)  일산화탄소(ppm)  500m내지하철역갯수   지하철이용객      미세_봄     미세_여름     미세_가을     미세_겨울     초미세_봄    초미세_여름    초미세_가을    초미세_겨울  건축년도  \
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727 -0.194810 0.402356  0.023169  -0.123956            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000  2003   
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667 -0.206834 0.225646  0.040863  -0.030205            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000  2003   

   전용면적(㎡)  층   거래금액  면적당 금액  전체_추정교통량_전체시간  승용차_추정교통량_전체시간  버스_추정교통량_전체시간  화물차_추정교통량_전체시간    혼잡빈도강도    혼잡시간강도  유동인구_전체  유동인구_출퇴근  유동인구_출근  유동인구_퇴근  남자10대유동인구  남자20대유동인구  남자30대유동인구  남자40대유동인구  남자50대유동인구  남자60대유동인구  여자10대유동인구  여자20대유동인구  여자30대유동인구  여자40대유동인구  여자50대유동인구  여자60대유동인구  
0       75  4  21700     288     486.400000      368.370000       2.760000      115.240000 42.687500 67.075000 5.832431  6.927639 6.594444 7.260833   2.365833   7.491667   9.765833  13.972500  20.946667  25.994167   1.820833   6.397500   6.496667  10.760000  17.704167  16.250833  
1       75  4  21700     288     156.265714      129.308571       0.402857       26.500000 60.881429 69.982857 6.176354  7.160278 7.342500 6.978056   1.715833   5.220833   9.853333  15.887500  22.269167  30.544167   1.487500   4.343333   5.940833  10.950000  20.195000  19.827500

## 8-3. 요일별 유동인구 (주중,주말 평균)

In [147]:
def point(data): 
    lon=data["lon"]
    lat=data["lat"]
    return [(x, y) for x, y in zip(lon, lat)] 

In [148]:
# 16번 데이터 전처리
df_16["point"]=point(df_16)

# point기준으로 groupby
df_16_2=df_16.groupby(df_16["point"]).mean().reset_index()

df_16_2["평일유동인구"]=(df_16_2["FLOW_POP_CNT_MON"]+df_16_2["FLOW_POP_CNT_TUS"]+df_16_2["FLOW_POP_CNT_WED"]+df_16_2["FLOW_POP_CNT_THU"]+df_16_2["FLOW_POP_CNT_FRI"])/5
df_16_2["주말유동인구"]=(df_16_2["FLOW_POP_CNT_SAT"]+df_16_2["FLOW_POP_CNT_SUN"])/2

df_16_2 = df_16_2.sort_values(by = ['lon']).reset_index(drop = True)

In [149]:
def find_optim_pop(station, new):
    # 각 정류장에 대해 반복
    for i in tqdm(range(len(station))):
        
        # 계산량을 줄이기 위한 filter
        ## lon
        # sort_lon = new.sort_values(by = ['lon']).reset_index(drop = True)
        idx_lon = bisect_left(new['lon'], station['lon'][i])
        fltr_lon = new[(new['lon']<new.loc[idx_lon, 'lon']+0.001)&(new['lon']>new.loc[idx_lon, 'lon']-0.001)].reset_index(drop = True)
        ## lat
        sort_lat = fltr_lon.sort_values(by = ['lat']).reset_index(drop = True)
        idx_lat = bisect_left(sort_lat['lat'], station['lat'][i])
        fltr_lat = sort_lat[(sort_lat['lat']<sort_lat.loc[idx_lat, 'lat']+0.01)&(sort_lat['lat']>sort_lat.loc[idx_lat, 'lat']-0.01)].reset_index(drop = True)

        # filter된 데이터의 거리 계산
        distance = []
        for j in range(len(fltr_lat)):
            station_name = tuple(station[['lon','lat']].iloc[i])
            fltr_name = tuple(fltr_lat[['lon','lat']].iloc[j])
            distance.append(haversine(station_name, fltr_name, unit = 'km'))
            
        station['pop_평일'][i] = fltr_lat['평일유동인구'][np.argmin(distance)]
        station['pop_주말'][i] = fltr_lat['주말유동인구'][np.argmin(distance)]
        
    return station

In [150]:
busdf["pop_평일"], busdf["pop_주말"] = 0.1, 0.1
busdf = find_optim_pop(busdf, df_16_2)

print(busdf.shape)
busdf.head(2)

100%|██████████| 516/516 [02:24<00:00,  3.58it/s]

(516, 121)


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도   강수량상관관계   온도상관관계  미세먼지상관관계  초미세먼지상관관계  nlp_cluster  미세먼지(㎍/㎥)  초미세먼지(㎍/㎥)  오존(ppm)  이산화질소(ppm)  아황산가스(ppm)  일산화탄소(ppm)  500m내지하철역갯수   지하철이용객      미세_봄     미세_여름     미세_가을     미세_겨울     초미세_봄    초미세_여름    초미세_가을    초미세_겨울  건축년도  \
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727 -0.194810 0.402356  0.023169  -0.123956            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000  2003   
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667 -0.206834 0.225646  0.040863  -0.030205            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000  2003   

   전용면적(㎡)  층   거래금액  면적당 금액  전체_추정교통량_전체시간  승용차_추정교통량_전체시간  버스_추정교통량_전체시간  화물차_추정교통량_전체시간    혼잡빈도강도    혼잡시간강도  유동인구_전체  유동인구_출퇴근  유동인구_출근  유동인구_퇴근  남자10대유동인구  남자20대유동인구  남자30대유동인구  남자40대유동인구  남자50대유동인구  남자60대유동인구  여자10대유동인구  여자20대유동인구  여자30대유동인구  여자40대유동인구  여자50대유동인구  여자60대유동인구     pop_평일     pop_주말  
0       75  4  21700     288     486.400000      368.370000       2.760000      115.240000 42.687500 67.075000 5.832431  6.927639 6.594444 7.260833   2.365833   7.491667   9.765833  13.972500  20.946667  25.994167   1.820833   6.397500   6.496667  10.760000  17.704167  16.250833 124.747167 178.410417  
1       75  4  21700     288     156.265714      129.308571       0.402857       26.500000 60.881429 69.982857 6.176354  7.160278 7.342500 6.978056   1.715833   5.220833   9.853333  15.887500  22.269167  30.544167   1.487500   4.343333   5.940833  10.950000  20.195000  19.827500 132.046000 189.586667

## 8-4. 디지털 정보화 지수 
* 출처 : 과학기술정보통신부 **[2020 디지털 정보격차실태조사 보고서](https://www.nia.or.kr/site/nia_kor/ex/bbs/View.do?cbIdx=81623&bcIdx=23112&parentSeq=23112)** > 연령별 디지털정보화 수준
* 10대 $\cdot$ 1.119 + 20대 $\cdot$ 1.223 + 30대 $\cdot$ 1.208 + 40대 $\cdot$ 1.116 + 50대 $\cdot$ 0.992 + 60대 $\cdot$ (0.778 + 0.388)/2

In [151]:
busdf[["남자디지털정보지수"]] = busdf.progress_apply(lambda x : x["남자10대유동인구"]*1.119 +  x["남자10대유동인구"]*1.223 + \
                                         x["남자30대유동인구"]*1.208 +  x["남자40대유동인구"]*1.116 + \
                                         x["남자50대유동인구"]*0.992 +  x["남자60대유동인구"]*0.558 , axis=1) 
busdf[["여자디지털정보지수"]] = busdf.progress_apply(lambda x : x["여자10대유동인구"]*1.119 +  x["여자10대유동인구"]*1.223 + \
                                         x["여자30대유동인구"]*1.208 +  x["여자40대유동인구"]*1.116 + \
                                         x["여자50대유동인구"]*0.992 +  x["여자60대유동인구"]*0.558 , axis=1)

busdf[["디지털정보지수"]] = busdf.progress_apply(lambda x : (x["남자디지털정보지수"] + x["여자디지털정보지수"])/2, axis=1)
busdf = busdf.drop(['남자디지털정보지수', '여자디지털정보지수'], axis=1)         

100%|██████████| 516/516 [00:00<00:00, 14866.57it/s]


# 9. 기타 데이터 

## 9-1. 주차장 구획수

In [152]:
def close_park(park,station):
    for i in tqdm(range(len(park))):
        # 거리 계산
        distance = []
        for j in range(len(station)):
            station_name = tuple(station[['lon','lat']].iloc[j])
            park_name = tuple(park[['lon','lat']].iloc[i])
            distance.append(haversine(park_name, station_name, unit = 'km'))
            
        # 최소
        park['정류소ID'][i] = station['정류소ID'][np.argmin(distance)]
            
    return park

In [153]:
df_12['정류소ID']=0
df_12= close_park(df_12, busdf)

100%|██████████| 70/70 [01:08<00:00,  1.02it/s]


In [154]:
busdf["주차구획수"]=0
for i in tqdm(range(len(busdf))):
    for j in range(len(df_12)):
        if df_12["정류소ID"][j]==busdf["정류소ID"][i]:
            busdf["주차구획수"][i]=df_12["주차구획수"][j]
        else:
            0

100%|██████████| 516/516 [00:00<00:00, 799.94it/s]


## 9-2. 인구 

### 고령인구 

In [155]:
# 경도, 위도를 point로 변환
busdf['lon'] = busdf['lon'].astype(float)
busdf['lat'] = busdf['lat'].astype(float)
busdf['point'] = busdf.progress_apply(lambda row : Point([row['lon'], row['lat']]), axis=1)

100%|██████████| 516/516 [00:00<00:00, 25281.35it/s]


In [156]:
df_17["val"] =df_17["val"].fillna(0) 

busdf["고령인구"]=0
for i in tqdm(range(len(df_17))):
    for j in range(len(busdf)) :
        if busdf["point"][j].within(df_17["geometry"][i]):
            busdf["고령인구"][j]=df_17["val"][i]

100%|██████████| 12500/12500 [15:10<00:00, 13.73it/s]


### 생산가능인구 

In [157]:
df_18["val"] =df_18["val"].fillna(0)

busdf["생산가능인구"]=0
for i in tqdm(range(len(df_18))) :
    for j in range(len(busdf)) :
        if busdf["point"][j].within(df_18["geometry"][i]):
            busdf["생산가능인구"][j]=df_18["val"][i]  

100%|██████████| 12500/12500 [15:14<00:00, 13.67it/s]


### 유소년인구

In [158]:
df_19["val"] =df_19["val"].fillna(0) 

busdf["유소년인구"]=0
for i in tqdm(range(len(df_19))) :
    for j in range(len(busdf)) :
        if busdf["point"][j].within(df_19["geometry"][i]):
            busdf["유소년인구"][j]=df_19["val"][i]  

100%|██████████| 12500/12500 [15:04<00:00, 13.82it/s]


### 전체 인구 & 비율 

In [159]:
busdf["전체인구"]=busdf["고령인구"]+busdf["생산가능인구"]+busdf["유소년인구"]

# 비율 
busdf["고령_전체"]=busdf["고령인구"]/busdf["전체인구"]
busdf["생산_전체"]=busdf["생산가능인구"]/busdf["전체인구"]
busdf["유소년_전체"]=busdf["유소년인구"]/busdf["전체인구"]

busdf["고령_전체"] =busdf["고령_전체"].fillna(0) 
busdf["생산_전체"] =busdf["생산_전체"].fillna(0) 
busdf["유소년_전체"] =busdf["유소년_전체"].fillna(0) 

busdf = busdf.drop(["전체인구"], axis=1)

# 10. 상권 데이터 
* 출처 : **[공공데이터포털](https://www.data.go.kr/data/15012005/fileData.do)** 소상공인시장진흥공단_상가(상권)정보_경기 

In [160]:
store = pd.read_excel(current_path+'/data/store_info.xlsx')

# 수원 데이터만 가져오기 
loc_code = list(df_30["EMD_CD"].astype(float) * 100)  # 수원시 법정동 코드 목록 

suwon_store = store[store["법정동코드"].isin(loc_code)]
print(suwon_store.shape)

(51862, 39)


In [161]:
print('커피전문점/카페/다방', ":", suwon_store[suwon_store.상권업종소분류명 == '커피전문점/카페/다방'].shape[0])

print('편의점', ":", suwon_store[(suwon_store.상권업종소분류명 == '편의점') & (suwon_store.상호명.str.contains('GS25|세븐일레븐|CU'))].shape[0] + \
      suwon_store[(suwon_store.상호명.str.contains('이마트')) & (suwon_store.지점명.str.contains('24'))].shape[0] + \
      suwon_store[suwon_store.상호명 == '이마트24'].shape[0])

print('학원', ":", suwon_store[suwon_store.상권업종중분류명 == '학원-보습교습입시'].shape[0] + \
      suwon_store[suwon_store.상권업종중분류명 == '학원-어학'].shape[0])

print('세탁소/빨래방', ":", suwon_store[suwon_store.상권업종소분류명 == '세탁소/빨래방'].shape[0], '\n')

# 마트 
print('이마트' , ":", suwon_store[(suwon_store.지점명.str.contains('24') == False) & (suwon_store.상호명 == '이마트')].shape[0])
print('홈플러스' , ":", suwon_store[suwon_store.상호명 == '홈플러스'].shape[0])
print('롯데마트' , ":", suwon_store[suwon_store.상호명 == '롯데마트'].shape[0])
print('하나로마트' , ":", suwon_store[suwon_store.상호명 == '하나로마트'].shape[0], '\n')

# 백화점 
print('AK플라자' , ":", suwon_store[suwon_store.상호명 == 'AK플라자백화점'].shape[0])
print('NC백화점' , ":", suwon_store[(suwon_store.상호명 == 'NC백화점') & (suwon_store.지점명 == 'NC터미널점')].shape[0])
print('갤러리아백화점' , ":", suwon_store[suwon_store.상호명 == '갤러리아백화점'].shape[0])
print('롯데몰' , ":", suwon_store[suwon_store.상호명 == '롯데몰'].shape[0])

커피전문점/카페/다방 : 2156
편의점 : 839
학원 : 1657
세탁소/빨래방 : 727 

이마트 : 6
홈플러스 : 5
롯데마트 : 4
하나로마트 : 9 

AK플라자 : 1
NC백화점 : 1
갤러리아백화점 : 1
롯데몰 : 1


In [162]:
mart = pd.concat([suwon_store[(suwon_store.지점명.str.contains('24') == False) & (suwon_store.상호명 == '이마트')], 
                  suwon_store[suwon_store.상호명 == '홈플러스'], suwon_store[suwon_store.상호명 == '롯데마트'], 
                  suwon_store[suwon_store.상호명 == '하나로마트']], axis=0)

dep = pd.concat([suwon_store[suwon_store.상호명 == 'AK플라자백화점'], 
                 suwon_store[(suwon_store.상호명 == 'NC백화점') & (suwon_store.지점명 == 'NC터미널점')], 
                 suwon_store[suwon_store.상호명 == '갤러리아백화점'], suwon_store[suwon_store.상호명 == '롯데몰']] , axis=0)

conv = pd.concat([suwon_store[(suwon_store.상권업종소분류명 == '편의점') & (suwon_store.상호명.str.contains('GS25|세븐일레븐|CU'))], 
                  suwon_store[(suwon_store.상호명.str.contains('이마트')) & (suwon_store.지점명.str.contains('24'))], 
                  suwon_store[suwon_store.상호명 == '이마트24']], axis=0)

cafe = suwon_store[suwon_store.상권업종소분류명 == '커피전문점/카페/다방']

academy = pd.concat([suwon_store[suwon_store.상권업종중분류명 == '학원-보습교습입시'],
                     suwon_store[suwon_store.상권업종중분류명 == '학원-어학']], axis=0)

laundry = suwon_store[suwon_store.상권업종소분류명 == '세탁소/빨래방']


mart.shape, dep.shape, conv.shape, cafe.shape, academy.shape, laundry.shape

((24, 39), (4, 39), (839, 39), (2156, 39), (1657, 39), (727, 39))

In [163]:
def close_store(bus, store, column) : 
    for i in tqdm(range(len(bus))) : 
        distance = [] 
        for j in range(len(store)) : 
            stationloc = tuple(bus[['lon','lat']].iloc[i])
            storeloc = tuple(store[['경도','위도']].iloc[j])
            distance.append(haversine(stationloc, storeloc, unit = 'm'))
            
        distance = [d for d in distance if d <= 500] 
        bus[column][i] = len(distance)
        
    return bus

In [164]:
def close_store2(bus, store, column):
    # 각 정류장에 대해 반복
    for i in tqdm(range(len(bus))):
        
        distance = []
        
        # 계산량을 줄이기 위한 filter
        ## lon
        # sort_lon = store.sort_values(by = ['lon']).reset_index(drop = True)
        idx_lon = bisect_left(store['경도'], bus['lon'][i])
        if 1 < idx_lon < len(store) : 
            fltr_lon = store[(store['경도']<store.loc[idx_lon, '경도']+0.001)&(store['경도']>store.loc[idx_lon, '경도']-0.001)].reset_index(drop = True)
            ## lat
            sort_lat = fltr_lon.sort_values(by = ['위도']).reset_index(drop = True)
            idx_lat = bisect_left(sort_lat['위도'], bus['lat'][i])
            
            if 1 < idx_lat < len(sort_lat) : 
                fltr_lat = sort_lat[(sort_lat['위도']<sort_lat.loc[idx_lat, '위도']+0.01)&(sort_lat['위도']>sort_lat.loc[idx_lat, '위도']-0.01)].reset_index(drop = True)

                # filter된 데이터의 거리 계산
                for j in range(len(fltr_lat)):
                    bus_name = tuple(bus[['lon','lat']].iloc[i])
                    fltr_name = tuple(fltr_lat[['경도','위도']].iloc[j])
                    distance.append(haversine(bus_name, fltr_name, unit = 'm'))
        
        distance = [d for d in distance if d <= 500]
            
        if len(distance) > 0 : 
            bus[column][i] = len(distance)
        else : 
            bus[column][i] = 0 
        
    return bus

In [165]:
busdf["500미터내마트개수"], busdf["500미터내백화점개수"] = 0, 0
busdf = close_store(busdf, mart, "500미터내마트개수")
busdf = close_store(busdf, dep, "500미터내백화점개수")

100%|██████████| 516/516 [00:04<00:00, 120.39it/s]


In [166]:
conv = conv.sort_values(by = ['경도']).reset_index(drop = True)
cafe = cafe.sort_values(by = ['경도']).reset_index(drop = True)
academy = academy.sort_values(by = ['경도']).reset_index(drop = True)
laundry = laundry.sort_values(by = ['경도']).reset_index(drop = True)

busdf["500미터내편의점개수"], busdf["500미터내카페개수"], busdf["500미터내학원개수"], busdf["500미터세탁소개수"] = 0, 0, 0, 0
busdf = close_store2(busdf, conv, "500미터내편의점개수")
busdf = close_store2(busdf, cafe, "500미터내카페개수") 
busdf = close_store2(busdf, academy, "500미터내학원개수") 
busdf = close_store2(busdf, laundry, "500미터세탁소개수")

100%|██████████| 516/516 [00:04<00:00, 106.96it/s]


# 11. Data Save 

In [167]:
end = time.time()

print("=====" * 20)
print("\t Data Preprocessing Takes : {:.4} min".format((end-start) / 60))
print("=====" * 20)

	 Data Preprocessing Takes : 113.2 min


In [168]:
busdf = busdf.drop(["point"], axis=1)

In [169]:
busdf.to_excel(current_path+'/busdata/bus_final.xlsx', index = False, encoding = 'CP949')

In [170]:
print(busdf.shape)
busdf.head(3)

(516, 135)


정류소ID                  정류장명       쉘터      LED      LCD  LED+LCD복합형      알뜰형        lon       lat  중앙차로여부  운행노선수  정류장유형수    초승_환승비율  초승_승차비율   초승_하차비율  환승_승차비율  환승_하차비율   승차_하차비율     승차비율     환승비율     하차비율   전체 승차 건수      초승 건수     환승 건수   전체 하차 건수  노선유형_경기순환버스(직행좌석형)  노선유형_광역급행형시내버스  노선유형_맞춤형시내버스  노선유형_일반형시내버스  노선유형_좌석형시내버스  노선유형_직행좌석형시내버스    전체승하차건수  승차많은버스  환승많은버스  하차많은버스  상행버스정류장운행시간  하행버스정류장운행시간  주중배차간격(분)   주중승차비율   주중환승비율   주중하차비율  주중전체승하차건수  주중배차간격_15분  주중배차간격_60분     주중배차횟수  주중승차많은버스  주중환승많은버스  주중하차많은버스   주중대기시간노출도  평균주중배차간격  주말배차간격(분)   주말승차비율   주말환승비율   주말하차비율   주말전체승하차건수  주말배차간격_15분  주말배차간격_60분     주말배차횟수  주말승차많은버스  주말환승많은버스  주말하차많은버스   주말대기시간노출도  평균주말배차간격  공휴일승차비율  공휴일환승비율  공휴일하차비율  공휴일전체승하차건수  공휴일승차많은버스  공휴일환승많은버스  공휴일하차많은버스  공휴일대기시간노출도   강수량상관관계   온도상관관계  미세먼지상관관계  초미세먼지상관관계  nlp_cluster  미세먼지(㎍/㎥)  초미세먼지(㎍/㎥)  오존(ppm)  이산화질소(ppm)  아황산가스(ppm)  일산화탄소(ppm)  500m내지하철역갯수   지하철이용객      미세_봄     미세_여름     미세_가을     미세_겨울     초미세_봄    초미세_여름    초미세_가을    초미세_겨울  건축년도  \
0  200000006  광교공원.경기대수원캠퍼스입구.연무시장 0.000000 0.000000 0.000000    1.000000 0.000000 127.029464 37.300014       0      9       1  12.771369 0.909413 14.400385 0.090587 1.121787 15.522172 0.764578 0.075057 0.160365 601.614903 559.026465 42.588438 269.979548                   0               0             0             8             0               0 871.594451       7       0       0    17.833333    18.083333  98.312500 0.763982 0.063101 0.172917 807.824583    4.000000    4.000000 503.707749         7         0         0 4639.473467 11.500000  99.625000 0.766371 0.093460 0.140169 1021.791501    3.000000    4.000000 427.025438         7         0         0 6716.120271 17.500000 0.789157 0.074057 0.136786  885.335606   7.000000   0.000000   0.000000 6002.522727 -0.194810 0.402356  0.023169  -0.123956            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000  2003   
1  200000008                   문암골 0.000000 0.000000 0.000000    1.000000 0.000000 127.027700 37.308946       0      1       1 258.513761 0.996147  2.109605 0.003853 0.008161  2.117766 0.676640 0.002617 0.320742  77.498630  77.200000  0.298630  36.594521                   0               0             0             1             0               0 114.093151       1       0       0    16.000000    17.500000   6.000000 0.767258 0.004407 0.228335  75.630522    1.000000    0.000000 167.500000         1         0         0  350.168675  6.000000   6.000000 0.599555 0.001160 0.399285  199.009615    1.000000    0.000000 167.500000         0         0         0  717.288462  6.000000 0.611576 0.000643 0.387781  172.777778   0.000000   0.000000   0.000000  634.666667 -0.206834 0.225646  0.040863  -0.030205            8  49.458333   24.166667 0.018250    0.034458    0.003042    0.704167            0  3954133 61.000000 36.333333 39.666667 60.833333 28.333333 15.666667 17.166667 35.500000  2003   
2  200000036               풍림아파트입구 1.000000 0.000000 0.000000    1.000000 0.000000 126.995257 37.297929       0      1       2  10.415812 0.912402  0.673753 0.087598 0.064686  0.738438 0.387562 0.037209 0.575229  73.186301  66.775342  6.410959  99.109589                   0               0             0             1             0               0 172.295890       0       0       0    17.833333    17.833333   8.000000 0.390197 0.039952 0.569850 195.915663    1.000000    0.000000 133.750000         0         0         0  674.184739  8.000000  10.500000 0.381641 0.028005 0.590354  123.605769    1.000000    0.000000 101.904762         0         0         0  531.663462 10.500000 0.352423 0.024229 0.623348  100.888889   0.000000   0.000000   0.000000  399.000000 -0.013023 0.087172  0.058419   0.056768            3  39.458333   23.125000 0.027917    0.024917    0.002958    0.562500            0  3954133 48.000000 29.833333 32.333333 47.666667 26.000000 16.333333 17.666667 32.500000  1989   

   전용면적(㎡)

In [171]:
busdf.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 516 entries, 0 to 515
Data columns (total 135 columns):
 #   Column              Dtype  
---  ------              -----  
 0   정류소ID               int64  
 1   정류장명                object 
 2   쉘터                  float64
 3   LED                 float64
 4   LCD                 float64
 5   LED+LCD복합형          float64
 6   알뜰형                 float64
 7   lon                 float64
 8   lat                 float64
 9   중앙차로여부              int64  
 10  운행노선수               int64  
 11  정류장유형수              int64  
 12  초승_환승비율             float64
 13  초승_승차비율             float64
 14  초승_하차비율             float64
 15  환승_승차비율             float64
 16  환승_하차비율             float64
 17  승차_하차비율             float64
 18  승차비율                float64
 19  환승비율                float64
 20  하차비율                float64
 21  전체 승차 건수            float64
 22  초승 건수               float64
 23  환승 건수               float64
 24  전체 하차 건수            float64
 25

In [172]:
# 결측값 체크 
busdf.isnull().sum()

정류소ID                 0
정류장명                  0
쉘터                    0
LED                   0
LCD                   0
LED+LCD복합형            0
알뜰형                   0
lon                   0
lat                   0
중앙차로여부                0
운행노선수                 0
정류장유형수                0
초승_환승비율               0
초승_승차비율               0
초승_하차비율               0
환승_승차비율               0
환승_하차비율               0
승차_하차비율               0
승차비율                  0
환승비율                  0
하차비율                  0
전체 승차 건수              0
초승 건수                 0
환승 건수                 0
전체 하차 건수              0
노선유형_경기순환버스(직행좌석형)    0
노선유형_광역급행형시내버스        0
노선유형_맞춤형시내버스          0
노선유형_일반형시내버스          0
노선유형_좌석형시내버스          0
노선유형_직행좌석형시내버스        0
전체승하차건수               0
승차많은버스                0
환승많은버스                0
하차많은버스                0
상행버스정류장운행시간           0
하행버스정류장운행시간           0
주중배차간격(분)             0
주중승차비율                0
주중환승비율                0
주중하차비율                0
주중전체승하차건수       